In [1]:
import numpy as np 
import pandas as pd 
import math

In [2]:
data=pd.read_csv("cmc_data.csv")

In [3]:
data.columns=["id","age","wife_education","husband_education","children", "religion", "wife_work", "husband_work","living_standard","exposure","Class"]

In [4]:
data.set_index("id", inplace=True)

In [5]:
data_class=data.groupby("Class")

In [6]:
data_class.size()

Class
1    628
2    333
3    511
dtype: int64

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1472 entries, 2 to 1473
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                1472 non-null   int64
 1   wife_education     1472 non-null   int64
 2   husband_education  1472 non-null   int64
 3   children           1472 non-null   int64
 4   religion           1472 non-null   int64
 5   wife_work          1472 non-null   int64
 6   husband_work       1472 non-null   int64
 7   living_standard    1472 non-null   int64
 8   exposure           1472 non-null   int64
 9   Class              1472 non-null   int64
dtypes: int64(10)
memory usage: 126.5 KB


In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(data, data.Class, train_size=.7)

In [10]:
train_file_x=X_train.to_csv("kkk.csv")

In [11]:
test_file_x=X_test.to_csv("kk_test.csv")

In [12]:
train_file_y=Y_train.to_csv("lll.csv")

In [13]:
test_file_y=Y_test.to_csv("lll_test.csv")

In [14]:
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(1030, 10) (442, 10) (1030,) (442,)


In [15]:
X_train

,age,wife_education,husband_education,children,religion,wife_work,husband_work,living_standard,exposure,Class
id,,,,,,,,,,
1298,35,4,4,5,1,1,1,4,0,2
1445,22,4,4,2,1,1,3,4,0,3
1409,36,4,4,3,1,1,2,4,0,3
1202,25,4,4,3,1,1,1,2,0,1
1093,28,3,3,5,1,1,3,3,0,1
...,...,...,...,...,...,...,...,...,...,...
1271,41,4,4,4,0,0,2,4,0,2
1226,30,2,2,7,1,1,3,4,0,2
954,39,1,2,2,1,0,2,4,0,3


In [16]:
Y_train

id
1298    2
1445    3
1409    3
1202    1
1093    1
       ..
1271    2
1226    2
954     3
575     2
218     1
Name: Class, Length: 1030, dtype: int64

In [17]:
gb=X_train.groupby("Class")

In [18]:
for Class, Class_df in gb:
    print(Class)
    print(Class_df)

1
      age  wife_education  husband_education  children  religion  wife_work  \
id                                                                            
1202   25               4                  4         3         1          1   
1093   28               3                  3         5         1          1   
40     28               2                  2         1         1          1   
1186   31               3                  2         1         1          1   
126    31               3                  4         2         1          1   
...   ...             ...                ...       ...       ...        ...   
1047   28               2                  3         1         1          1   
297    49               3                  4         9         1          1   
1030   43               3                  4        10         1          1   
366    20               2                  3         3         1          1   
218    34               3                  2      

In [19]:
gb.get_group(1)

,age,wife_education,husband_education,children,religion,wife_work,husband_work,living_standard,exposure,Class
id,,,,,,,,,,
1202,25,4,4,3,1,1,1,2,0,1
1093,28,3,3,5,1,1,3,3,0,1
40,28,2,2,1,1,1,2,4,0,1
1186,31,3,2,1,1,1,3,4,0,1
126,31,3,4,2,1,1,1,2,1,1
...,...,...,...,...,...,...,...,...,...,...
1047,28,2,3,1,1,1,3,1,0,1
297,49,3,4,9,1,1,1,4,0,1
1030,43,3,4,10,1,1,3,3,0,1


In [20]:
class_samples=gb.get_group(1).sample(n=20)
print(class_samples)

      age  wife_education  husband_education  children  religion  wife_work  \
id                                                                            
1203   47               1                  1         4         1          1   
281    43               2                  3         6         1          0   
251    34               4                  4         3         0          1   
127    45               4                  4         1         1          1   
1180   23               3                  2         0         1          1   
1134   28               3                  4         0         1          0   
1087   27               4                  4         2         1          0   
199    30               1                  1         5         1          1   
1138   37               3                  4         4         1          0   
1150   36               4                  3         3         1          0   
1076   45               3                  4        

In [21]:
print(type(class_samples))

<class 'pandas.core.frame.DataFrame'>


In [22]:
mean_sum=class_samples["age"].mean() + class_samples["wife_education"].mean() + class_samples["husband_education"].mean() + class_samples["children"].mean() + class_samples["religion"].mean() + class_samples["wife_work"].mean() + class_samples["husband_work"].mean() + class_samples["living_standard"].mean() + class_samples["exposure"].mean()

In [23]:
similar_val_1=mean_sum/5
print(similar_val_1)

9.940000000000001


In [24]:
class_2_samples=gb.get_group(2).sample(n=20)
print(class_2_samples)

      age  wife_education  husband_education  children  religion  wife_work  \
id                                                                            
1285   24               4                  4         2         1          1   
1272   35               1                  2         9         1          0   
498    26               4                  4         1         0          1   
479    42               4                  4         6         1          1   
1230   27               3                  3         2         1          1   
618    35               2                  2         6         1          1   
1312   42               3                  3         4         0          1   
507    22               4                  4         1         1          1   
455    36               4                  4         2         1          1   
1252   34               3                  4         4         1          1   
460    42               4                  4        

In [25]:
mean_sum_2=class_2_samples["age"].mean() + class_2_samples["wife_education"].mean() + class_2_samples["husband_education"].mean() + class_2_samples["children"].mean() + class_2_samples["religion"].mean() + class_2_samples["wife_work"].mean() + class_2_samples["husband_work"].mean() + class_2_samples["living_standard"].mean() + class_2_samples["exposure"].mean()

In [26]:
similar_val_2=mean_sum_2/5
print(similar_val_2)

9.68


In [27]:
class_3_samples=gb.get_group(3).sample(n=20)
print(class_3_samples)

      age  wife_education  husband_education  children  religion  wife_work  \
id                                                                            
833    21               3                  4         2         1          1   
1387   33               4                  4         5         1          1   
692    29               2                  4         3         1          1   
890    33               4                  4         4         1          1   
698    27               3                  4         2         1          1   
1404   26               4                  4         3         1          1   
878    42               4                  4         5         1          1   
1416   36               3                  4         9         1          1   
697    42               4                  4         7         1          1   
1364   22               4                  4         1         1          1   
712    39               3                  4        

In [28]:
mean_sum_3=class_3_samples["age"].mean() + class_3_samples["wife_education"].mean() + class_3_samples["husband_education"].mean() + class_3_samples["children"].mean() + class_3_samples["religion"].mean() + class_3_samples["wife_work"].mean() + class_3_samples["husband_work"].mean() + class_3_samples["living_standard"].mean() + class_3_samples["exposure"].mean()

In [29]:
similar_val_3=mean_sum_3/5
print(similar_val_3)

9.67


In [78]:
sim_23=abs(similar_val_2 - similar_val_3)
sim_23=sim_23/10
sim_23=1 - sim_23
sim_21=abs(similar_val_2 - similar_val_1)
sim_21=sim_21/10
sim_21=1 - sim_21
sim_13=abs(similar_val_3 - similar_val_1)
sim_13=sim_13/10
sim_13=1 - sim_13

print("Similarity between 2 and 3: ", sim_23)
print("Similarity between 2 and 1: ", sim_21)
print("Similarity between 1 and 3: ", sim_13)

Similarity between 2 and 3:  0.999
Similarity between 2 and 1:  0.9739999999999999
Similarity between 1 and 3:  0.9729999999999999


In [31]:
gb.size()

Class
1    433
2    233
3    364
dtype: int64

In [32]:
m=math.ceil((103+24)/2)

In [33]:
print(m)

64


In [34]:
len(gb)

3

In [35]:
 from sklearn.neighbors import KNeighborsClassifier

In [36]:
neigh = KNeighborsClassifier(n_neighbors=5)

In [37]:
neigh.fit(X_train, Y_train)

KNeighborsClassifier()

In [38]:
result=neigh.kneighbors(X_train, return_distance=True)

In [39]:
print(type(result))

<class 'tuple'>


In [40]:
print(result)

(array([[0.        , 1.        , 1.        , 1.        , 1.        ],
       [0.        , 1.41421356, 1.41421356, 1.73205081, 1.73205081],
       [0.        , 1.        , 1.        , 1.41421356, 1.41421356],
       ...,
       [0.        , 2.64575131, 2.64575131, 2.82842712, 3.        ],
       [0.        , 0.        , 0.        , 1.        , 1.41421356],
       [0.        , 1.73205081, 2.23606798, 2.23606798, 2.64575131]]), array([[   0,  508,   51,  314,  770],
       [   1,  244,  863,  987,  827],
       [   2,  299,   67,  914,  114],
       ...,
       [1027,  550,  927,  681,  122],
       [1025, 1028,  860,  502,  923],
       [1029,  703,  994,  985,  856]], dtype=int64))


In [41]:
arr1=result[0]

In [42]:
print(type(arr1))

<class 'numpy.ndarray'>


In [43]:
print(arr1.ndim)

2


In [44]:
arr2=result[1]

In [45]:
print(type(arr2))

<class 'numpy.ndarray'>


In [46]:
print(arr1.ndim)

2


In [47]:
print(arr2)

[[   0  508   51  314  770]
 [   1  244  863  987  827]
 [   2  299   67  914  114]
 ...
 [1027  550  927  681  122]
 [1025 1028  860  502  923]
 [1029  703  994  985  856]]


In [48]:
print(arr1)

[[0.         1.         1.         1.         1.        ]
 [0.         1.41421356 1.41421356 1.73205081 1.73205081]
 [0.         1.         1.         1.41421356 1.41421356]
 ...
 [0.         2.64575131 2.64575131 2.82842712 3.        ]
 [0.         0.         0.         1.         1.41421356]
 [0.         1.73205081 2.23606798 2.23606798 2.64575131]]


In [49]:
#print(arr1)

In [50]:
print(arr1.size)

5150


In [51]:
addVal=[]
s=1
for i in arr1:
    _sum=int(i[0] + i[1] + i[2] + i[3] + i[4])
    addVal.append(_sum)
    print(i ," ", _sum, " ") 
    s=s+1

[0. 1. 1. 1. 1.]   4  
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6  
[0.         1.         1.         1.41421356 1.41421356]   4  
[0.         1.73205081 2.         2.         2.        ]   7  
[0.         2.23606798 2.23606798 2.44948974 2.44948974]   9  
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5  
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6  
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5  
[0.         2.         2.23606798 2.23606798 2.23606798]   8  
[0.         1.73205081 1.73205081 2.         2.        ]   7  
[0.         1.41421356 2.         2.         2.        ]   7  
[0.         1.         1.41421356 1.41421356 1.41421356]   5  
[0.         2.23606798 2.23606798 2.23606798 2.44948974]   9  
[0.         1.         1.41421356 1.73205081 1.73205081]   5  
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6  
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6  
[0.         1.41421356 1.4142135

[0.         1.41421356 1.41421356 1.73205081 2.        ]   6  
[0.         2.         2.         2.23606798 2.23606798]   8  
[0.         1.73205081 2.         2.         2.23606798]   7  
[0.         1.         1.         1.41421356 1.41421356]   4  
[0.         1.73205081 2.23606798 2.44948974 2.82842712]   9  
[0.         1.         1.         1.41421356 1.41421356]   4  
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6  
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7  
[0.         1.         1.41421356 2.         2.        ]   6  
[0.         0.         1.         1.41421356 1.41421356]   3  
[0.         1.         1.41421356 1.73205081 2.        ]   6  
[0.         1.         1.41421356 1.41421356 1.41421356]   5  
[0.         1.73205081 2.23606798 2.44948974 2.44948974]   8  
[0.         2.23606798 2.44948974 2.82842712 2.82842712]   10  
[0.         1.41421356 2.         2.         2.        ]   7  
[0.         1.41421356 2.         2.         2.2360679

[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5  
[0.         1.73205081 1.73205081 2.         2.        ]   7  
[0.         2.         2.         2.23606798 2.23606798]   8  
[0.         2.44948974 2.44948974 2.44948974 2.44948974]   9  
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7  
[0.         1.41421356 2.         2.         2.23606798]   7  
[0.         1.73205081 1.73205081 2.         2.23606798]   7  
[0.         2.44948974 2.44948974 2.44948974 2.44948974]   9  
[0.         1.41421356 2.23606798 2.23606798 2.23606798]   8  
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6  
[0.         1.73205081 1.73205081 2.         2.        ]   7  
[0.         2.44948974 2.44948974 2.44948974 2.64575131]   9  
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6  
[0.         1.         1.41421356 1.41421356 2.        ]   5  
[0.         1.         1.41421356 1.41421356 1.41421356]   5  
[0.         1.41421356 1.41421356 1.41421356 1.41421356

[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6  
[0.         1.41421356 2.         2.         2.44948974]   7  
[0.         1.         1.73205081 1.73205081 1.73205081]   6  
[0.         1.         1.         1.         1.41421356]   4  
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6  
[0.         1.         1.41421356 1.41421356 1.41421356]   5  
[0.         1.41421356 1.73205081 2.         2.        ]   7  
[0.         0.         1.         1.         1.41421356]   3  
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5  
[0.         1.73205081 2.         2.         2.        ]   7  
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7  
[0.         1.73205081 2.         2.23606798 2.23606798]   8  
[0.         1.41421356 1.73205081 2.         2.        ]   7  
[0.         0.         1.         1.41421356 1.41421356]   3  
[0.         1.73205081 1.73205081 2.         2.        ]   7  
[0.         1.         1.41421356 2.         2.        

[0.         2.44948974 2.64575131 2.64575131 2.64575131]   10  
[0.         1.         1.41421356 1.41421356 1.41421356]   5  
[0.         1.41421356 1.73205081 1.73205081 1.73205081]   6  
[0.         1.73205081 2.         2.         2.44948974]   8  
[0.         1.         1.41421356 1.73205081 1.73205081]   5  
[0.         2.23606798 2.23606798 2.23606798 2.44948974]   9  
[0.         1.73205081 2.         2.         2.        ]   7  
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5  
[0.         1.         1.41421356 1.41421356 1.73205081]   5  
[0.         1.73205081 1.73205081 1.73205081 2.        ]   7  
[0.         0.         1.         1.41421356 1.41421356]   3  
[0.         1.         1.41421356 2.         2.        ]   6  
[0. 0. 0. 1. 1.]   2  
[0.         1.         1.41421356 1.41421356 1.73205081]   5  
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6  
[0.         1.73205081 1.73205081 1.73205081 2.23606798]   7  
[0.         1.41421356 1.414213

[0.         1.73205081 2.         2.23606798 2.44948974]   8  
[0.         1.73205081 1.73205081 2.         2.        ]   7  
[0.         1.         1.         1.73205081 1.73205081]   5  
[0.         1.73205081 1.73205081 1.73205081 1.73205081]   6  
[0.         1.41421356 1.41421356 1.73205081 2.        ]   6  
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6  
[0.         1.41421356 1.41421356 2.23606798 2.44948974]   7  
[0.         2.23606798 2.23606798 2.23606798 2.23606798]   8  
[0.         2.         2.         2.23606798 2.23606798]   8  
[0.         1.41421356 1.73205081 1.73205081 2.        ]   6  
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5  
[0.         1.41421356 1.41421356 1.41421356 1.73205081]   5  
[0.         1.73205081 2.23606798 2.23606798 2.44948974]   8  
[0.         2.         2.23606798 2.23606798 2.44948974]   8  
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5  
[0.         1.73205081 1.73205081 1.73205081 2.        

In [52]:
print(len(addVal))

1030


In [53]:
print(addVal)

[4, 6, 4, 7, 9, 5, 6, 5, 8, 7, 7, 5, 9, 5, 6, 6, 6, 5, 7, 10, 5, 5, 6, 10, 5, 7, 9, 6, 9, 6, 8, 6, 8, 8, 9, 7, 9, 8, 8, 5, 7, 4, 5, 8, 9, 6, 4, 5, 3, 7, 6, 4, 5, 7, 4, 5, 5, 7, 5, 10, 6, 5, 8, 6, 8, 7, 8, 5, 7, 8, 4, 9, 7, 5, 9, 8, 6, 7, 10, 10, 5, 9, 10, 4, 5, 6, 10, 7, 11, 5, 6, 5, 5, 6, 10, 7, 7, 5, 6, 6, 5, 9, 9, 6, 10, 9, 6, 5, 5, 6, 5, 5, 5, 6, 5, 5, 5, 5, 6, 5, 6, 6, 9, 6, 5, 8, 7, 10, 6, 4, 9, 10, 11, 4, 6, 7, 13, 6, 9, 6, 5, 6, 6, 8, 6, 7, 9, 9, 7, 4, 5, 4, 9, 5, 8, 5, 7, 7, 11, 6, 7, 10, 4, 4, 7, 5, 5, 7, 5, 2, 5, 8, 11, 6, 7, 8, 8, 5, 9, 5, 7, 9, 6, 7, 5, 6, 8, 6, 5, 9, 6, 5, 6, 8, 7, 6, 8, 7, 4, 9, 4, 6, 7, 6, 3, 6, 5, 8, 10, 7, 7, 10, 5, 6, 8, 8, 6, 5, 8, 4, 6, 9, 10, 6, 6, 6, 5, 5, 5, 7, 9, 5, 6, 3, 5, 6, 7, 4, 7, 8, 5, 4, 9, 7, 5, 4, 8, 8, 5, 5, 7, 4, 7, 6, 8, 6, 7, 3, 5, 4, 3, 5, 7, 9, 4, 9, 8, 4, 5, 6, 5, 7, 9, 5, 5, 3, 8, 6, 4, 6, 7, 6, 5, 10, 5, 9, 4, 7, 4, 6, 4, 7, 8, 8, 5, 7, 5, 6, 5, 4, 2, 7, 5, 5, 3, 5, 9, 4, 4, 11, 9, 4, 11, 5, 5, 12, 5, 9, 6, 8, 8, 6, 4, 6, 6, 

In [54]:
arr3=np.array(addVal)

In [55]:
print(type(arr3))

<class 'numpy.ndarray'>


In [56]:
print(arr3.size)

1030


In [57]:
print(arr3)

[ 4  6  4 ... 11  2  8]


In [58]:
g=1
for i in addVal:
    print(g ," ", i) 
    g=g+1

1   4
2   6
3   4
4   7
5   9
6   5
7   6
8   5
9   8
10   7
11   7
12   5
13   9
14   5
15   6
16   6
17   6
18   5
19   7
20   10
21   5
22   5
23   6
24   10
25   5
26   7
27   9
28   6
29   9
30   6
31   8
32   6
33   8
34   8
35   9
36   7
37   9
38   8
39   8
40   5
41   7
42   4
43   5
44   8
45   9
46   6
47   4
48   5
49   3
50   7
51   6
52   4
53   5
54   7
55   4
56   5
57   5
58   7
59   5
60   10
61   6
62   5
63   8
64   6
65   8
66   7
67   8
68   5
69   7
70   8
71   4
72   9
73   7
74   5
75   9
76   8
77   6
78   7
79   10
80   10
81   5
82   9
83   10
84   4
85   5
86   6
87   10
88   7
89   11
90   5
91   6
92   5
93   5
94   6
95   10
96   7
97   7
98   5
99   6
100   6
101   5
102   9
103   9
104   6
105   10
106   9
107   6
108   5
109   5
110   6
111   5
112   5
113   5
114   6
115   5
116   5
117   5
118   5
119   6
120   5
121   6
122   6
123   9
124   6
125   5
126   8
127   7
128   10
129   6
130   4
131   9
132   10
133   11
134   4
135   6
136   7
137   1

In [59]:
newarr = arr3.reshape(1030, 1)

In [60]:
print(newarr.ndim)

2


In [61]:
new_arr2=np.append(arr2, newarr, axis=1)

In [62]:
print(type(new_arr2))

<class 'numpy.ndarray'>


In [63]:
print(new_arr2)

[[   0  508   51  314  770    4]
 [   1  244  863  987  827    6]
 [   2  299   67  914  114    4]
 ...
 [1027  550  927  681  122   11]
 [1025 1028  860  502  923    2]
 [1029  703  994  985  856    8]]


In [64]:
print(new_arr2[0])

[  0 508  51 314 770   4]


In [65]:
print(type(Y_train))

<class 'pandas.core.series.Series'>


In [66]:
arr2

array([[   0,  508,   51,  314,  770],
       [   1,  244,  863,  987,  827],
       [   2,  299,   67,  914,  114],
       ...,
       [1027,  550,  927,  681,  122],
       [1025, 1028,  860,  502,  923],
       [1029,  703,  994,  985,  856]], dtype=int64)

In [67]:
print(new_arr2[0][1],  new_arr2[0][2],  new_arr2[0][3], new_arr2[0][4],new_arr2[0][5])

508 51 314 770 4


In [68]:
# Creating and populating a dictionary
new_dist={}
for i, v in Y_train.iteritems():
    new_dist[i]=v

In [69]:
print(new_dist)

{1298: 2, 1445: 3, 1409: 3, 1202: 1, 1093: 1, 1233: 2, 938: 3, 695: 3, 40: 1, 1443: 3, 1186: 1, 689: 3, 126: 1, 321: 1, 64: 1, 887: 3, 824: 3, 165: 1, 912: 3, 1100: 1, 1073: 1, 630: 2, 1381: 3, 1272: 2, 1151: 1, 22: 1, 1086: 1, 605: 2, 1224: 2, 1369: 3, 1033: 1, 9: 1, 1120: 1, 460: 2, 1000: 3, 560: 2, 516: 2, 527: 2, 128: 1, 903: 3, 1074: 1, 791: 3, 115: 1, 535: 2, 106: 1, 132: 1, 982: 3, 1400: 3, 586: 2, 1454: 3, 334: 1, 418: 2, 935: 3, 189: 1, 1107: 1, 1375: 3, 861: 3, 610: 2, 857: 3, 315: 1, 1350: 3, 1307: 2, 391: 1, 1214: 1, 56: 1, 1452: 3, 289: 1, 782: 3, 3: 1, 1158: 1, 1247: 2, 18: 1, 207: 1, 1152: 1, 1276: 2, 705: 3, 1013: 1, 885: 3, 1046: 1, 229: 1, 1349: 3, 60: 1, 1418: 3, 1216: 2, 976: 3, 252: 1, 950: 3, 1138: 1, 700: 3, 306: 1, 1005: 1, 25: 1, 1275: 2, 845: 3, 53: 1, 913: 3, 1431: 3, 793: 3, 671: 3, 924: 3, 406: 1, 19: 1, 1212: 1, 831: 3, 1167: 1, 530: 2, 858: 3, 753: 3, 783: 3, 1426: 3, 1260: 2, 787: 3, 1472: 3, 636: 2, 455: 2, 309: 1, 1082: 1, 495: 2, 294: 1, 485: 2, 854: 

In [70]:
# Creating and populating a dictionary
new_dist2={}
s=0
for i, v in Y_train.iteritems():
    new_dist2[s]=v
    s=s+1

In [71]:
print(new_dist2)

{0: 2, 1: 3, 2: 3, 3: 1, 4: 1, 5: 2, 6: 3, 7: 3, 8: 1, 9: 3, 10: 1, 11: 3, 12: 1, 13: 1, 14: 1, 15: 3, 16: 3, 17: 1, 18: 3, 19: 1, 20: 1, 21: 2, 22: 3, 23: 2, 24: 1, 25: 1, 26: 1, 27: 2, 28: 2, 29: 3, 30: 1, 31: 1, 32: 1, 33: 2, 34: 3, 35: 2, 36: 2, 37: 2, 38: 1, 39: 3, 40: 1, 41: 3, 42: 1, 43: 2, 44: 1, 45: 1, 46: 3, 47: 3, 48: 2, 49: 3, 50: 1, 51: 2, 52: 3, 53: 1, 54: 1, 55: 3, 56: 3, 57: 2, 58: 3, 59: 1, 60: 3, 61: 2, 62: 1, 63: 1, 64: 1, 65: 3, 66: 1, 67: 3, 68: 1, 69: 1, 70: 2, 71: 1, 72: 1, 73: 1, 74: 2, 75: 3, 76: 1, 77: 3, 78: 1, 79: 1, 80: 3, 81: 1, 82: 3, 83: 2, 84: 3, 85: 1, 86: 3, 87: 1, 88: 3, 89: 1, 90: 1, 91: 1, 92: 2, 93: 3, 94: 1, 95: 3, 96: 3, 97: 3, 98: 3, 99: 3, 100: 1, 101: 1, 102: 1, 103: 3, 104: 1, 105: 2, 106: 3, 107: 3, 108: 3, 109: 3, 110: 2, 111: 3, 112: 3, 113: 2, 114: 2, 115: 1, 116: 1, 117: 2, 118: 1, 119: 2, 120: 3, 121: 2, 122: 1, 123: 1, 124: 3, 125: 3, 126: 2, 127: 1, 128: 2, 129: 1, 130: 1, 131: 1, 132: 1, 133: 2, 134: 2, 135: 1, 136: 1, 137: 1, 138: 

In [72]:
# Creating and populating a dictionary
new_dist3={}
s=0
for i, v in Y_train.iteritems():
    new_dist3[s]=i
    s=s+1

In [73]:
print(new_dist3)

{0: 1298, 1: 1445, 2: 1409, 3: 1202, 4: 1093, 5: 1233, 6: 938, 7: 695, 8: 40, 9: 1443, 10: 1186, 11: 689, 12: 126, 13: 321, 14: 64, 15: 887, 16: 824, 17: 165, 18: 912, 19: 1100, 20: 1073, 21: 630, 22: 1381, 23: 1272, 24: 1151, 25: 22, 26: 1086, 27: 605, 28: 1224, 29: 1369, 30: 1033, 31: 9, 32: 1120, 33: 460, 34: 1000, 35: 560, 36: 516, 37: 527, 38: 128, 39: 903, 40: 1074, 41: 791, 42: 115, 43: 535, 44: 106, 45: 132, 46: 982, 47: 1400, 48: 586, 49: 1454, 50: 334, 51: 418, 52: 935, 53: 189, 54: 1107, 55: 1375, 56: 861, 57: 610, 58: 857, 59: 315, 60: 1350, 61: 1307, 62: 391, 63: 1214, 64: 56, 65: 1452, 66: 289, 67: 782, 68: 3, 69: 1158, 70: 1247, 71: 18, 72: 207, 73: 1152, 74: 1276, 75: 705, 76: 1013, 77: 885, 78: 1046, 79: 229, 80: 1349, 81: 60, 82: 1418, 83: 1216, 84: 976, 85: 252, 86: 950, 87: 1138, 88: 700, 89: 306, 90: 1005, 91: 25, 92: 1275, 93: 845, 94: 53, 95: 913, 96: 1431, 97: 793, 98: 671, 99: 924, 100: 406, 101: 19, 102: 1212, 103: 831, 104: 1167, 105: 530, 106: 858, 107: 753,

In [74]:
#print(new_dist[204])

In [75]:
    neigh_count=[]
    s=0
    for i, v in new_dist2.items():
        c1=0
        c2=0
        c3=0
        if int(v) == 1:
            c1=c1+1
        elif int(v) == 2:
            c2=c2+1
        else:
            c3=c3+1
        for x in range(1,5):
            if new_dist2[new_arr2[i][x]]==1:
                c1=c1+1
            elif new_dist2[new_arr2[i][x]]==2:
                c2=c2+1
            else:
                c3=c3+1
        print(i," ",new_dist3[i]," ",c1," ",c2," ",c3," ",new_arr2[i][5])
    #real_new=new_dist3[i]," ",new_arr2[i][1]," ",new_arr2[i][2]," ",new_arr2[i][3]," ",new_arr2[i][4]," ",new_arr2[i][5]
    
    #print(i," ",real_new)

0   1298   1   4   0   4
1   1445   0   0   5   6
2   1409   0   1   4   4
3   1202   3   2   0   7
4   1093   1   2   2   9
5   1233   0   2   3   5
6   938   0   0   5   6
7   695   0   0   5   5
8   40   4   1   0   8
9   1443   0   3   2   7
10   1186   5   0   0   7
11   689   0   0   5   5
12   126   5   0   0   9
13   321   3   2   0   5
14   64   5   0   0   6
15   887   0   2   3   6
16   824   0   0   5   6
17   165   2   3   0   5
18   912   0   1   4   7
19   1100   4   0   1   10
20   1073   5   0   0   5
21   630   0   5   0   5
22   1381   0   1   4   6
23   1272   2   2   1   10
24   1151   3   2   0   5
25   22   5   0   0   7
26   1086   5   0   0   9
27   605   2   1   2   6
28   1224   2   2   1   9
29   1369   0   1   4   6
30   1033   4   1   0   8
31   9   4   1   0   6
32   1120   4   1   0   8
33   460   0   2   3   8
34   1000   0   3   2   9
35   560   0   3   2   7
36   516   1   2   2   9
37   527   0   1   4   8
38   128   5   0   0   8
39   903   0   1   

388   1280   0   4   1   5
389   1142   5   0   0   7
390   993   0   2   3   7
391   1228   0   4   1   5
392   1467   0   2   3   8
393   251   5   0   0   7
394   925   0   0   5   9
395   764   0   0   5   6
396   1031   2   3   0   8
397   46   5   0   0   6
398   775   0   2   3   5
399   1263   1   3   1   5
400   795   0   0   5   7
401   962   0   0   5   3
402   104   3   2   0   8
403   754   0   0   5   5
404   345   5   0   0   6
405   698   0   1   4   6
406   1194   5   0   0   3
407   424   0   1   4   10
408   1462   0   2   3   8
409   124   5   0   0   7
410   662   0   3   2   6
411   1112   3   2   0   5
412   902   0   2   3   7
413   1246   0   4   1   8
414   990   0   1   4   9
415   1251   2   2   1   7
416   910   0   0   5   7
417   591   0   2   3   7
418   428   1   3   1   9
419   1171   5   0   0   8
420   443   1   4   0   6
421   526   2   1   2   7
422   937   1   2   2   9
423   280   5   0   0   6
424   1037   3   2   0   5
425   510   0   5   0   5

751   562   2   3   0   8
752   733   0   1   4   10
753   1236   0   3   2   5
754   643   0   0   5   6
755   1003   5   0   0   8
756   1354   0   0   5   5
757   1108   4   1   0   9
758   916   0   2   3   7
759   573   0   4   1   5
760   169   5   0   0   5
761   1283   1   3   1   7
762   727   0   1   4   3
763   967   0   0   5   6
764   168   5   0   0   2
765   204   3   2   0   5
766   1101   3   2   0   6
767   58   4   1   0   7
768   1287   1   2   2   6
769   678   0   1   4   8
770   1227   0   5   0   4
771   1337   0   0   5   5
772   848   1   0   4   7
773   1059   4   1   0   8
774   714   0   0   5   5
775   1315   0   3   2   5
776   883   0   0   5   5
777   326   5   0   0   6
778   82   4   1   0   5
779   852   0   2   3   7
780   363   5   0   0   8
781   762   0   2   3   9
782   457   0   4   1   2
783   256   2   3   0   6
784   651   0   2   3   7
785   1057   5   0   0   9
786   353   5   0   0   6
787   506   1   3   1   5
788   395   4   1   0   4
7

In [76]:
#neigh_count=[]
#s=0
#for i, v in new_dist.items():
#    c1=0
#    c2=0
 #   c3=0
  #  if int(v) == 1:
   #     c1=c1+1
    #elif int(v) == 2:
     #   c2=c2+1
    #else:
     #   c3=c3+1
    #for x in range(1,5):
        #print(x)
     #   y=new_dist[new_arr2[s][x]]
      #  print(y)
    #s=s+1
        
            
    
#print(i," ",c1," ",c2," ",c3)
    