In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("thyroid.csv")

In [3]:
data.columns=["Resin ","Oxin","Onine","Hormone ","Tsh","Class"]

In [4]:
data.to_csv("thyroid.csv", index=None, header=True)

In [5]:
#from sklearn.model_selection import train_test_split

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(data, data.Class, train_size=.7)

In [8]:
#Z_train=pd.DataFrame(X_train)
#Z_test=pd.DataFrame(X_test)
#W_train=pd.DataFrame(Y_train)
#W_train=pd.DataFrame(Y_test)

In [33]:
print(type(Y_train))

<class 'pandas.core.series.Series'>


In [34]:
print(type(X_train))

<class 'pandas.core.frame.DataFrame'>


In [9]:
train_file_x=X_train.to_csv("xxx.csv")

In [10]:
test_file_x=X_test.to_csv("xx_test.csv")

In [11]:
train_file_y=Y_train.to_csv("yyy.csv")

In [12]:
test_file_y=Y_test.to_csv("yy_test.csv")

In [13]:
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(147, 6) (64, 6) (147,) (64,)


In [14]:
 from sklearn.neighbors import KNeighborsClassifier

In [15]:
neigh = KNeighborsClassifier(n_neighbors=5)

In [16]:
neigh.fit(X_train, Y_train)

KNeighborsClassifier()

In [17]:
result=neigh.kneighbors(X_train, return_distance=True)

In [18]:
print(result)

(array([[ 0.        ,  2.48797106,  3.07408523,  3.18590646,  4.54422711],
       [ 0.        ,  2.28691933,  2.44744765,  2.63438797,  2.69443872],
       [ 0.        ,  1.50665192,  1.7       ,  2.06155281,  2.2737634 ],
       [ 0.        ,  1.396424  ,  1.74642492,  1.94422221,  1.98746069],
       [ 0.        ,  1.9       ,  2.30867928,  2.3515952 ,  3.38969025],
       [ 0.        ,  1.46287388,  1.94422221,  2.29128785,  2.52784493],
       [ 0.        ,  2.01494417,  2.04694895,  2.28035085,  2.28473193],
       [ 0.        , 14.35339681, 19.55990798, 19.8708329 , 21.34783361],
       [ 0.        ,  3.43511281,  5.14392846,  7.76208735,  8.08888126],
       [ 0.        ,  1.87082869,  2.01990099,  3.21091887,  3.38821487],
       [ 0.        ,  1.3453624 ,  1.57797338,  1.89472953,  1.99499373],
       [ 0.        ,  2.73861279,  3.19687347,  4.20238028,  6.10491605],
       [ 0.        ,  1.8627936 ,  2.36643191,  2.61151297,  2.7513633 ],
       [ 0.        ,  1.22474487,  1.

In [19]:
arr1=result[0]

In [20]:
arr2=result[1]

In [21]:
#result[1]

In [22]:
#np.savetxt("foo1.csv", arr1, delimiter=",")

In [23]:
#np.savetxt("foo2.csv", arr2, delimiter=",")

In [24]:
print(arr1)

[[ 0.          2.48797106  3.07408523  3.18590646  4.54422711]
 [ 0.          2.28691933  2.44744765  2.63438797  2.69443872]
 [ 0.          1.50665192  1.7         2.06155281  2.2737634 ]
 [ 0.          1.396424    1.74642492  1.94422221  1.98746069]
 [ 0.          1.9         2.30867928  2.3515952   3.38969025]
 [ 0.          1.46287388  1.94422221  2.29128785  2.52784493]
 [ 0.          2.01494417  2.04694895  2.28035085  2.28473193]
 [ 0.         14.35339681 19.55990798 19.8708329  21.34783361]
 [ 0.          3.43511281  5.14392846  7.76208735  8.08888126]
 [ 0.          1.87082869  2.01990099  3.21091887  3.38821487]
 [ 0.          1.3453624   1.57797338  1.89472953  1.99499373]
 [ 0.          2.73861279  3.19687347  4.20238028  6.10491605]
 [ 0.          1.8627936   2.36643191  2.61151297  2.7513633 ]
 [ 0.          1.22474487  1.33416641  1.3453624   1.85741756]
 [ 0.          1.3190906   1.81383571  2.01494417  2.11896201]
 [ 0.          7.0668239   7.18540187  9.69639108 10.50

In [25]:
#print(arr1)

In [26]:
for i in arr1:
    _sum=i[0] + i[1] + i[2] + i[3] + i[4]
    print(_sum) 
   

13.292189862128328
10.063193666835332
7.54196813032118
7.0745318249917295
9.949964730719667
8.226228872785965
8.62697589896431
75.13197129598102
24.430009873065877
10.489863421879335
6.8130590549889645
16.242782589884
9.592101784139203
5.761691244612265
7.266832488551696
34.450997529012604
16.11406227972301
12.728421865971058
9.205537393620968
27.496258989782653
10.850014867527154
8.572098753241185
15.293428288096528
7.379868509750143
24.464858395495153
19.94606744979819
6.729468040408763
9.156934741558992
27.882422083644645
12.595854890524478
6.396666971028556
9.794662970002731
86.62136506015356
9.457030126419
7.516612298744099
7.170066460632359
54.0971211734076
11.208033326830192
25.251714398740216
13.231914615541257
18.432887198175337
9.763399874294539
21.954741400479673
54.40068445793564
8.913149256030259
8.342216387267122
7.378786868007197
12.164526991467692
54.38143322286507
7.069238995154668
14.354858217485791
9.248065315243327
32.65269978054383
6.938986467972968
9.5717925292124

In [27]:
#for x in result:
    #print(x[0][1])

In [28]:
#for k in arr2:
 #   print(k[0])

In [29]:
#num_list = [0, 1, 2, 3, 4]
#for i in range(149):
    #for z in range(5):
        #print(i,z)
        