In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns 
#import matplotlib.pyplot as plt

In [2]:
#data=pd.read_csv("new-thyroid.data")

In [3]:
data=pd.read_csv("new-thyroid.csv")

In [8]:
data

,1,1.1,107,10.1,2.2,0.9,2.7
0,2,1,113,9.9,3.1,2.0,5.9
1,3,1,127,12.9,2.4,1.4,0.6
2,4,1,109,5.3,1.6,1.4,1.5
3,5,1,105,7.3,1.5,1.5,-0.1
4,6,1,105,6.1,2.1,1.4,7.0
...,...,...,...,...,...,...,...
209,211,3,118,6.5,1.3,1.7,11.5
210,212,3,139,4.2,0.7,4.3,6.3
211,213,3,103,5.1,1.4,1.2,5.0
212,214,3,97,4.7,1.1,2.1,12.6


In [4]:
data.columns=["id","Class","Oxin","Onine","Hormone ","Tsh","Resin"]

In [5]:
#data.to_csv("thyroid.csv", index=None, header=True)

In [6]:
data.set_index("id", inplace=True)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 214 entries, 2 to 215
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Class     214 non-null    int64  
 1   Oxin      214 non-null    int64  
 2   Onine     214 non-null    float64
 3   Hormone   214 non-null    float64
 4   Tsh       214 non-null    float64
 5   Resin     214 non-null    float64
dtypes: float64(4), int64(2)
memory usage: 11.7 KB


In [8]:
#from sklearn.model_selection import train_test_split

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(data, data.Class, train_size=.7)

In [11]:
#Z_train=pd.DataFrame(X_train)
#Z_test=pd.DataFrame(X_test)
#W_train=pd.DataFrame(Y_train)
#W_train=pd.DataFrame(Y_test)

In [12]:
print(type(Y_train))

<class 'pandas.core.series.Series'>


In [13]:
print(type(X_train))

<class 'pandas.core.frame.DataFrame'>


In [14]:
train_file_x=X_train.to_csv("xxx.csv")

In [15]:
test_file_x=X_test.to_csv("xx_test.csv")

In [16]:
train_file_y=Y_train.to_csv("yyy.csv")

In [17]:
test_file_y=Y_test.to_csv("yy_test.csv")

In [18]:
print(X_train)

     Class  Oxin  Onine  Hormone    Tsh  Resin
id                                            
38       1   106    9.4       1.5   0.8    0.5
208      3   112    2.6       0.7  41.0   19.0
187      3   120    6.8       2.1  10.4   38.6
110      1   102    9.5       1.4   1.1    1.6
166      2    99   13.0       3.6   0.7   -0.1
..     ...   ...    ...       ...   ...    ...
133      1   113    7.8       2.0   1.1    3.0
163      2    88   12.9       2.7   0.1    0.2
173      2    84   18.5       4.4   1.1   -0.3
142      1    98    5.7       0.4   1.3    2.8
105      1   114    8.4       1.6   1.6   -0.2

[149 rows x 6 columns]


In [19]:
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(149, 6) (65, 6) (149,) (65,)


In [20]:
 from sklearn.neighbors import KNeighborsClassifier

In [21]:
neigh = KNeighborsClassifier(n_neighbors=5)

In [22]:
neigh.fit(X_train, Y_train)

KNeighborsClassifier()

In [23]:
result=neigh.kneighbors(X_train, return_distance=True)

In [24]:
print(type(result))

<class 'tuple'>


In [25]:
print(result)

(array([[ 0.        ,  1.10905365,  1.63401346,  1.98997487,  2.10475652],
       [ 0.        , 23.48382422, 27.57752708, 29.31944747, 33.34516457],
       [ 0.        ,  4.6141088 , 10.95810203, 14.6116392 , 17.67682098],
       [ 0.        ,  1.94422221,  2.18632111,  2.32163735,  2.47588368],
       [ 0.        ,  0.53851648,  2.47790234,  2.4979992 ,  3.45108679],
       [ 0.        ,  0.53851648,  2.30867928,  2.61725047,  3.25576412],
       [ 0.        ,  2.04450483,  2.32594067,  2.43926218,  3.01827765],
       [ 0.        ,  2.66833281,  3.6796739 ,  3.96232255,  4.85798312],
       [ 0.        ,  3.7094474 ,  5.63471383,  6.18142378,  6.95053955],
       [ 0.        ,  1.91049732,  2.463737  ,  2.58069758,  2.67020598],
       [ 0.        ,  0.76157731,  1.356466  ,  1.79443584,  2.10475652],
       [ 0.        ,  2.00748599,  2.97657521,  3.13528308,  3.22800248],
       [ 0.        ,  1.9       ,  2.30867928,  2.3515952 ,  2.47790234],
       [ 0.        ,  0.94339811,  1.

In [26]:
arr1=result[0]

In [27]:
print(type(arr1))

<class 'numpy.ndarray'>


In [28]:
print(arr1.ndim)

2


In [29]:
arr2=result[1]

In [30]:
print(type(arr2))

<class 'numpy.ndarray'>


In [31]:
print(arr1.ndim)

2


In [32]:
#result[1]

In [33]:
#np.savetxt("foo1.csv", arr1, delimiter=",")

In [34]:
#np.savetxt("foo2.csv", arr2, delimiter=",")

In [35]:
print(arr2)

[[  0 111 139 102  13]
 [  1 109  34  43  92]
 [  2 113  80 122 100]
 [  3  24  94  26  47]
 [  4   5  12  91  19]
 [  5   4  12  91  19]
 [  6  45  32 117  38]
 [  7 118 136  27  85]
 [  8  63 145  25 119]
 [  9 135  62 116  40]
 [ 10 148  16  39  60]
 [ 11  23  53  74 105]
 [ 12 132   5  47   4]
 [ 13  81 102  94   0]
 [ 14 112  77  86  57]
 [ 15 121 131  66 125]
 [ 16  10 148  98  39]
 [ 17  97 102 116  81]
 [ 18  36  61  92 120]
 [ 19  91  67   5   4]
 [ 20  27 118  48   7]
 [ 21  52 141 146  96]
 [ 22 124 144  83 140]
 [ 23  11  75 104  74]
 [ 24  94   3  81  13]
 [ 25 114  91 143  71]
 [ 26 103 115   3 125]
 [ 27  20  48   7 118]
 [ 28  89  65 141  52]
 [ 29  72  57 148  98]
 [ 30  15  90 131 121]
 [ 31 122  80 113   2]
 [ 32  45  38  86 134]
 [ 33  68 125  66 115]
 [ 34  92  43 109  61]
 [ 35  45  95 134  32]
 [ 36  18  92  61 120]
 [ 37 105  74 124  88]
 [ 38  32  45 134  86]
 [ 39  98  16  10 144]
 [ 40 106  62  73 135]
 [ 41  93 137  83  46]
 [ 42  58 107 117  54]
 [ 43 120  

In [36]:
print(arr1)

[[ 0.          1.10905365  1.63401346  1.98997487  2.10475652]
 [ 0.         23.48382422 27.57752708 29.31944747 33.34516457]
 [ 0.          4.6141088  10.95810203 14.6116392  17.67682098]
 [ 0.          1.94422221  2.18632111  2.32163735  2.47588368]
 [ 0.          0.53851648  2.47790234  2.4979992   3.45108679]
 [ 0.          0.53851648  2.30867928  2.61725047  3.25576412]
 [ 0.          2.04450483  2.32594067  2.43926218  3.01827765]
 [ 0.          2.66833281  3.6796739   3.96232255  4.85798312]
 [ 0.          3.7094474   5.63471383  6.18142378  6.95053955]
 [ 0.          1.91049732  2.463737    2.58069758  2.67020598]
 [ 0.          0.76157731  1.356466    1.79443584  2.10475652]
 [ 0.          2.00748599  2.97657521  3.13528308  3.22800248]
 [ 0.          1.9         2.30867928  2.3515952   2.47790234]
 [ 0.          0.94339811  1.04403065  2.04694895  2.10475652]
 [ 0.          1.94679223  2.08326667  2.1023796   3.31963853]
 [ 0.          1.98494332  2.83901391  3.77226722  4.08

 [ 0.          0.76157731  1.47648231  2.19089023  2.51793566]]


In [37]:
#print(arr1)

In [38]:
print(arr1.size)

745


In [39]:
addVal=[]
s=1
for i in arr1:
    _sum=int(i[0] + i[1] + i[2] + i[3] + i[4])
    addVal.append(_sum)
    print(i ," ", _sum, " ") 
    s=s+1
   

[0.         1.10905365 1.63401346 1.98997487 2.10475652]   6  
[ 0.         23.48382422 27.57752708 29.31944747 33.34516457]   113  
[ 0.          4.6141088  10.95810203 14.6116392  17.67682098]   47  
[0.         1.94422221 2.18632111 2.32163735 2.47588368]   8  
[0.         0.53851648 2.47790234 2.4979992  3.45108679]   8  
[0.         0.53851648 2.30867928 2.61725047 3.25576412]   8  
[0.         2.04450483 2.32594067 2.43926218 3.01827765]   9  
[0.         2.66833281 3.6796739  3.96232255 4.85798312]   15  
[0.         3.7094474  5.63471383 6.18142378 6.95053955]   22  
[0.         1.91049732 2.463737   2.58069758 2.67020598]   9  
[0.         0.76157731 1.356466   1.79443584 2.10475652]   6  
[0.         2.00748599 2.97657521 3.13528308 3.22800248]   11  
[0.         1.9        2.30867928 2.3515952  2.47790234]   9  
[0.         0.94339811 1.04403065 2.04694895 2.10475652]   6  
[0.         1.94679223 2.08326667 2.1023796  3.31963853]   9  
[0.         1.98494332 2.83901391 3.772

In [40]:
print(len(addVal))

149


In [41]:
print(addVal)

[6, 113, 47, 8, 8, 8, 9, 15, 22, 9, 6, 11, 9, 6, 9, 12, 5, 12, 42, 11, 17, 30, 6, 10, 8, 15, 9, 14, 42, 10, 34, 49, 7, 10, 75, 9, 53, 8, 7, 6, 5, 12, 11, 40, 18, 6, 6, 10, 14, 8, 32, 10, 24, 13, 9, 11, 7, 9, 8, 7, 8, 35, 6, 25, 19, 45, 13, 17, 9, 6, 32, 12, 9, 6, 7, 8, 20, 8, 26, 26, 35, 6, 7, 5, 14, 23, 7, 18, 8, 42, 18, 11, 39, 10, 7, 10, 21, 10, 7, 8, 54, 12, 6, 10, 7, 8, 5, 8, 9, 59, 10, 6, 10, 44, 10, 10, 11, 9, 15, 18, 36, 11, 37, 18, 7, 9, 17, 15, 8, 66, 5, 12, 9, 5, 8, 7, 19, 14, 6, 7, 6, 33, 19, 9, 7, 19, 19, 15, 6]


In [42]:
arr3=np.array(addVal)

In [43]:
print(type(arr3))

<class 'numpy.ndarray'>


In [44]:
print(arr3.size)

149


In [45]:
print(arr3)

[  6 113  47   8   8   8   9  15  22   9   6  11   9   6   9  12   5  12
  42  11  17  30   6  10   8  15   9  14  42  10  34  49   7  10  75   9
  53   8   7   6   5  12  11  40  18   6   6  10  14   8  32  10  24  13
   9  11   7   9   8   7   8  35   6  25  19  45  13  17   9   6  32  12
   9   6   7   8  20   8  26  26  35   6   7   5  14  23   7  18   8  42
  18  11  39  10   7  10  21  10   7   8  54  12   6  10   7   8   5   8
   9  59  10   6  10  44  10  10  11   9  15  18  36  11  37  18   7   9
  17  15   8  66   5  12   9   5   8   7  19  14   6   7   6  33  19   9
   7  19  19  15   6]


In [46]:
g=1
for i in addVal:
    print(g ," ", i) 
    g=g+1

1   6
2   113
3   47
4   8
5   8
6   8
7   9
8   15
9   22
10   9
11   6
12   11
13   9
14   6
15   9
16   12
17   5
18   12
19   42
20   11
21   17
22   30
23   6
24   10
25   8
26   15
27   9
28   14
29   42
30   10
31   34
32   49
33   7
34   10
35   75
36   9
37   53
38   8
39   7
40   6
41   5
42   12
43   11
44   40
45   18
46   6
47   6
48   10
49   14
50   8
51   32
52   10
53   24
54   13
55   9
56   11
57   7
58   9
59   8
60   7
61   8
62   35
63   6
64   25
65   19
66   45
67   13
68   17
69   9
70   6
71   32
72   12
73   9
74   6
75   7
76   8
77   20
78   8
79   26
80   26
81   35
82   6
83   7
84   5
85   14
86   23
87   7
88   18
89   8
90   42
91   18
92   11
93   39
94   10
95   7
96   10
97   21
98   10
99   7
100   8
101   54
102   12
103   6
104   10
105   7
106   8
107   5
108   8
109   9
110   59
111   10
112   6
113   10
114   44
115   10
116   10
117   11
118   9
119   15
120   18
121   36
122   11
123   37
124   18
125   7
126   9
127   17
128   15
129   8
13

In [47]:
newarr = arr3.reshape(149, 1)

In [48]:
print(newarr.ndim)

2


In [49]:
new_arr2=np.append(arr2, newarr, axis=1)

In [50]:
print(new_arr2)

[[  0 111 139 102  13   6]
 [  1 109  34  43  92 113]
 [  2 113  80 122 100  47]
 [  3  24  94  26  47   8]
 [  4   5  12  91  19   8]
 [  5   4  12  91  19   8]
 [  6  45  32 117  38   9]
 [  7 118 136  27  85  15]
 [  8  63 145  25 119  22]
 [  9 135  62 116  40   9]
 [ 10 148  16  39  60   6]
 [ 11  23  53  74 105  11]
 [ 12 132   5  47   4   9]
 [ 13  81 102  94   0   6]
 [ 14 112  77  86  57   9]
 [ 15 121 131  66 125  12]
 [ 16  10 148  98  39   5]
 [ 17  97 102 116  81  12]
 [ 18  36  61  92 120  42]
 [ 19  91  67   5   4  11]
 [ 20  27 118  48   7  17]
 [ 21  52 141 146  96  30]
 [ 22 124 144  83 140   6]
 [ 23  11  75 104  74  10]
 [ 24  94   3  81  13   8]
 [ 25 114  91 143  71  15]
 [ 26 103 115   3 125   9]
 [ 27  20  48   7 118  14]
 [ 28  89  65 141  52  42]
 [ 29  72  57 148  98  10]
 [ 30  15  90 131 121  34]
 [ 31 122  80 113   2  49]
 [ 32  45  38  86 134   7]
 [ 33  68 125  66 115  10]
 [ 34  92  43 109  61  75]
 [ 35  45  95 134  32   9]
 [ 36  18  92  61 120  53]
 

In [51]:
#for x in result:
    #print(x[0][1])

In [52]:
#for k in arr2:
 #   print(k[0])

In [53]:
#num_list = [0, 1, 2, 3, 4]
#for i in range(149):
    #for z in range(5):
        #print(i,z)
        