In [1]:
import numpy as np 
import pandas as pd
import math

In [2]:
data=pd.read_csv("standard_scale.csv")


In [3]:
data.columns=["id","Class","Left-Weight","Left-Distance","Right-Weight","Right-Distance"]

In [4]:
data["Class"]=pd.factorize(data["Class"])[0] + 1

In [5]:
data.set_index("id", inplace=True)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 624 entries, 2 to 625
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Class           624 non-null    int64
 1   Left-Weight     624 non-null    int64
 2   Left-Distance   624 non-null    int64
 3   Right-Weight    624 non-null    int64
 4   Right-Distance  624 non-null    int64
dtypes: int64(5)
memory usage: 29.2 KB


In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, Y_train, Y_test = train_test_split(data, data.Class, train_size=.7)

In [9]:
train_file_x=X_train.to_csv("aaa.csv")

In [10]:
test_file_x=X_test.to_csv("aaa_test.csv")

In [11]:
train_file_y=Y_train.to_csv("bbb.csv")

In [12]:
test_file_y=Y_test.to_csv("yy_test.csv")

In [13]:
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(436, 5) (188, 5) (436,) (188,)


In [14]:
X_train

,Class,Left-Weight,Left-Distance,Right-Weight,Right-Distance
id,,,,,
574,1,5,3,5,4
557,2,5,3,2,2
56,2,1,3,2,1
42,1,1,2,4,2
296,2,3,2,5,1
...,...,...,...,...,...
587,2,5,4,3,2
370,1,3,5,4,5
544,1,5,2,4,4


In [15]:
Y_train

id
574    1
557    2
56     2
42     1
296    2
      ..
587    2
370    1
544    1
314    1
93     1
Name: Class, Length: 436, dtype: int64

In [16]:
gb=X_train.groupby("Class")

In [17]:
for Class, Class_df in gb:
    print(Class)
    print(Class_df)

1
     Class  Left-Weight  Left-Distance  Right-Weight  Right-Distance
id                                                                  
574      1            5              3             5               4
42       1            1              2             4               2
263      1            3              1             3               3
269      1            3              1             4               4
41       1            1              2             4               1
..     ...          ...            ...           ...             ...
395      1            4              1             4               5
370      1            3              5             4               5
544      1            5              2             4               4
314      1            3              3             3               4
93       1            1              4             4               3

[200 rows x 5 columns]
2
     Class  Left-Weight  Left-Distance  Right-Weight  Right-Distance
id    

In [18]:
gb.get_group(1)

,Class,Left-Weight,Left-Distance,Right-Weight,Right-Distance
id,,,,,
574,1,5,3,5,4
42,1,1,2,4,2
263,1,3,1,3,3
269,1,3,1,4,4
41,1,1,2,4,1
...,...,...,...,...,...
395,1,4,1,4,5
370,1,3,5,4,5
544,1,5,2,4,4


In [19]:
class_samples=gb.get_group(1).sample(n=20)
print(class_samples)

     Class  Left-Weight  Left-Distance  Right-Weight  Right-Distance
id                                                                  
163      1            2              2             3               3
199      1            2              3             5               4
475      1            4              4             5               5
123      1            1              5             5               3
93       1            1              4             4               3
264      1            3              1             3               4
393      1            4              1             4               3
168      1            2              2             4               3
500      1            4              5             5               5
515      1            5              1             3               5
298      1            3              2             5               3
155      1            2              2             1               5
225      1            2           

In [20]:
print(type(class_samples))

<class 'pandas.core.frame.DataFrame'>


In [21]:
mean_sum=class_samples["Left-Weight"].mean() + class_samples["Left-Distance"].mean() + class_samples["Right-Weight"].mean() + class_samples["Right-Distance"].mean()

In [22]:
similar_val_1=mean_sum/5
print(similar_val_1)

2.48


In [23]:
class_2_samples=gb.get_group(2).sample(n=20)
print(class_2_samples)

     Class  Left-Weight  Left-Distance  Right-Weight  Right-Distance
id                                                                  
296      2            3              2             5               1
401      2            4              2             1               1
242      2            2              5             4               2
286      2            3              2             3               1
498      2            4              5             5               3
359      2            3              5             2               4
461      2            4              4             3               1
411      2            4              2             3               1
231      2            2              5             2               1
453      2            4              4             1               3
463      2            4              4             3               3
305      2            3              3             1               5
403      2            4           

In [24]:
mean_sum_2=class_2_samples["Left-Weight"].mean() + class_2_samples["Left-Distance"].mean() + class_2_samples["Right-Weight"].mean() + class_2_samples["Right-Distance"].mean()

In [25]:
similar_val_2=mean_sum_2/5
print(similar_val_2)

2.31


In [26]:
class_3_samples=gb.get_group(3).sample(n=20)
print(class_3_samples)

     Class  Left-Weight  Left-Distance  Right-Weight  Right-Distance
id                                                                  
127      3            2              1             1               2
82       3            1              4             2               2
157      3            2              2             2               2
61       3            1              3             3               1
382      3            4              1             2               2
409      3            4              2             2               4
261      3            3              1             3               1
131      3            2              1             2               1
391      3            4              1             4               1
373      3            3              5             5               3
166      3            2              2             4               1
313      3            3              3             3               3
183      3            2           

In [27]:
mean_sum_3=class_3_samples["Left-Weight"].mean() + class_3_samples["Left-Distance"].mean() + class_3_samples["Right-Weight"].mean() + class_3_samples["Right-Distance"].mean()

In [28]:
similar_val_3=mean_sum_3/5
print(similar_val_3)

2.21


In [29]:
sim_23=abs(similar_val_3 - similar_val_2)
sim_23=sim_23/100
sim_23=1 - sim_23
sim_21=abs(similar_val_1 - similar_val_2)
sim_21=sim_21/100
sim_21=1 - sim_21
sim_13=abs(similar_val_3 - similar_val_1)
sim_13=sim_13/100
sim_13=1 - sim_13

print("Similarity between 2 and 3: ", sim_23)
print("Similarity between 2 and 1: ", sim_21)
print("Similarity between 1 and 3: ", sim_13)

Similarity between 2 and 3:  0.999
Similarity between 2 and 1:  0.9983
Similarity between 1 and 3:  0.9973


In [30]:
gb.size()

Class
1    200
2    197
3     39
dtype: int64

In [31]:
m=math.ceil((206+31)/2)

In [32]:
print(m)

119


In [33]:
len(gb)

3

In [34]:
 from sklearn.neighbors import KNeighborsClassifier

In [35]:
neigh = KNeighborsClassifier(n_neighbors=5)

In [36]:
neigh.fit(X_train, Y_train)

KNeighborsClassifier()

In [37]:
result=neigh.kneighbors(X_train, return_distance=True)

In [38]:
print(type(result))

<class 'tuple'>


In [39]:
print(result)

(array([[0.        , 1.        , 1.        , 1.        , 1.41421356],
       [0.        , 1.        , 1.        , 1.        , 1.        ],
       [0.        , 1.        , 1.        , 1.        , 1.41421356],
       ...,
       [0.        , 1.        , 1.        , 1.        , 1.        ],
       [0.        , 1.        , 1.        , 1.        , 1.41421356],
       [0.        , 1.        , 1.        , 1.        , 1.        ]]), array([[  0, 385, 171, 318, 409],
       [  1, 379, 421, 410, 353],
       [  2, 162, 380,  13, 394],
       ...,
       [433,  73,  38, 427, 265],
       [434, 202, 236,  36, 213],
       [435,  39, 239, 329,  95]], dtype=int64))


In [40]:
arr1=result[0]

In [41]:
print(type(arr1))

<class 'numpy.ndarray'>


In [42]:
print(arr1.ndim)

2


In [43]:
arr2=result[1]

In [44]:
print(type(arr2))

<class 'numpy.ndarray'>


In [45]:
print(arr1.ndim)

2


In [46]:
print(arr2)

[[  0 385 171 318 409]
 [  1 379 421 410 353]
 [  2 162 380  13 394]
 ...
 [433  73  38 427 265]
 [434 202 236  36 213]
 [435  39 239 329  95]]


In [47]:
print(arr1)

[[0.         1.         1.         1.         1.41421356]
 [0.         1.         1.         1.         1.        ]
 [0.         1.         1.         1.         1.41421356]
 ...
 [0.         1.         1.         1.         1.        ]
 [0.         1.         1.         1.         1.41421356]
 [0.         1.         1.         1.         1.        ]]


In [48]:
#print(arr1)

In [49]:
print(arr1.size)

2180


In [50]:
addVal=[]
s=1
for i in arr1:
    _sum=int(i[0] + i[1] + i[2] + i[3] + i[4])
    addVal.append(_sum)
    print(i ," ", _sum, " ") 
    s=s+1

[0.         1.         1.         1.         1.41421356]   4  
[0. 1. 1. 1. 1.]   4  
[0.         1.         1.         1.         1.41421356]   4  
[0. 1. 1. 1. 1.]   4  
[0.         1.         1.41421356 1.41421356 1.41421356]   5  
[0. 1. 1. 1. 1.]   4  
[0. 1. 1. 1. 1.]   4  
[0. 1. 1. 1. 1.]   4  
[0. 1. 1. 1. 1.]   4  
[0.         1.         1.         1.         1.41421356]   4  
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5  
[0. 1. 1. 1. 1.]   4  
[0. 1. 1. 1. 1.]   4  
[0. 1. 1. 1. 1.]   4  
[0.         1.         1.         1.41421356 1.41421356]   4  
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5  
[0. 1. 1. 1. 1.]   4  
[0. 1. 1. 1. 1.]   4  
[0.         1.         1.         1.41421356 1.41421356]   4  
[0.         1.         1.         1.         1.41421356]   4  
[0. 1. 1. 1. 1.]   4  
[0.         1.41421356 1.41421356 1.73205081 1.73205081]   6  
[0.         1.         1.         1.41421356 1.41421356]   4  
[0. 1. 1. 1. 1.]   4  
[0.     

[0.         1.         1.         1.41421356 1.41421356]   4  
[0. 1. 1. 1. 1.]   4  
[0. 1. 1. 1. 1.]   4  
[0. 1. 1. 1. 1.]   4  
[0.         1.         1.         1.         1.41421356]   4  
[0. 1. 1. 1. 1.]   4  
[0.         1.         1.         1.41421356 1.41421356]   4  
[0. 1. 1. 1. 1.]   4  
[0. 1. 1. 1. 1.]   4  
[0.         1.41421356 1.41421356 1.41421356 1.41421356]   5  
[0. 1. 1. 1. 1.]   4  
[0.         1.         1.         1.         1.41421356]   4  
[0. 1. 1. 1. 1.]   4  
[0.         1.         1.         1.         1.41421356]   4  
[0. 1. 1. 1. 1.]   4  
[0. 1. 1. 1. 1.]   4  
[0. 1. 1. 1. 1.]   4  
[0.         1.         1.41421356 1.41421356 1.41421356]   5  
[0. 1. 1. 1. 1.]   4  
[0. 1. 1. 1. 1.]   4  
[0. 1. 1. 1. 1.]   4  
[0. 1. 1. 1. 1.]   4  
[0.         1.         1.41421356 1.41421356 1.41421356]   5  
[0. 1. 1. 1. 1.]   4  
[0. 1. 1. 1. 1.]   4  
[0.         1.         1.41421356 1.41421356 1.41421356]   5  
[0.         1.41421356 1.41421356 1.414213

In [51]:
print(len(addVal))

436


In [52]:
print(addVal)

[4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 6, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 5, 5, 4, 4, 4, 4, 5, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 5, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 5, 4, 5, 5, 5, 4, 4, 4, 4, 5, 4, 4, 4, 4, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 4, 4, 4, 4, 5, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 4, 4, 4, 4, 4, 4, 6, 4, 5, 5, 5, 4, 4, 4, 4, 4, 5, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 5, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 5, 4, 4, 5, 5, 4, 4, 4, 4, 5, 4, 5, 4, 4, 5, 4, 4, 5, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 

In [53]:
arr3=np.array(addVal)

In [54]:
print(type(arr3))

<class 'numpy.ndarray'>


In [55]:
print(arr3.size)

436


In [56]:
print(arr3)

[4 4 4 4 5 4 4 4 4 4 5 4 4 4 4 5 4 4 4 4 4 6 4 4 4 4 4 5 4 4 4 4 4 5 5 4 4
 4 4 4 4 4 4 4 4 5 4 4 4 4 5 5 4 4 4 4 5 4 5 4 4 4 4 4 4 4 4 4 5 4 4 5 4 4
 4 4 4 5 4 4 4 4 4 5 4 4 4 4 4 4 4 4 4 4 4 4 4 5 4 4 4 5 4 4 4 4 4 4 4 5 4
 4 4 4 4 4 4 5 4 5 5 5 4 4 4 4 5 4 4 4 4 5 5 4 4 4 4 4 4 4 4 4 5 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 6 4 4 4 4 5 4 4 4 5 4 4 4 4 4 4 4 4 4 5 5 4 4 4 4
 4 4 6 4 5 5 5 4 4 4 4 4 5 4 5 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 4 5 4 4 4 4
 4 4 4 4 4 4 4 6 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 4 4 4
 4 4 5 4 5 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 4 4 4 4 4 4 4 5 4 4 4 4 5 4 4 5 5
 4 4 4 4 5 4 5 4 4 5 4 4 5 4 4 5 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 4 4
 4 4 4 4 5 5 5 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 4 4 4 4 4 4 4 4 4 5 4 4 4 5
 4 4 4 4 4 4 4 4 4 4 4 5 4 4 4 4 4 4 5 4 4 4 4 4 5 4 4 4 4 4 4 4 4 5 5 4 4
 4 4 4 4 4 4 5 4 5 4 4 4 4 4 4 5 4 5 4 5 4 4 4 4 4 5 4 4 4]


In [57]:
g=1
for i in addVal:
    print(g ," ", i) 
    g=g+1

1   4
2   4
3   4
4   4
5   5
6   4
7   4
8   4
9   4
10   4
11   5
12   4
13   4
14   4
15   4
16   5
17   4
18   4
19   4
20   4
21   4
22   6
23   4
24   4
25   4
26   4
27   4
28   5
29   4
30   4
31   4
32   4
33   4
34   5
35   5
36   4
37   4
38   4
39   4
40   4
41   4
42   4
43   4
44   4
45   4
46   5
47   4
48   4
49   4
50   4
51   5
52   5
53   4
54   4
55   4
56   4
57   5
58   4
59   5
60   4
61   4
62   4
63   4
64   4
65   4
66   4
67   4
68   4
69   5
70   4
71   4
72   5
73   4
74   4
75   4
76   4
77   4
78   5
79   4
80   4
81   4
82   4
83   4
84   5
85   4
86   4
87   4
88   4
89   4
90   4
91   4
92   4
93   4
94   4
95   4
96   4
97   4
98   5
99   4
100   4
101   4
102   5
103   4
104   4
105   4
106   4
107   4
108   4
109   4
110   5
111   4
112   4
113   4
114   4
115   4
116   4
117   4
118   5
119   4
120   5
121   5
122   5
123   4
124   4
125   4
126   4
127   5
128   4
129   4
130   4
131   4
132   5
133   5
134   4
135   4
136   4
137   4
138   4
139 

In [58]:
newarr = arr3.reshape(436, 1)

In [59]:
print(newarr.ndim)

2


In [60]:
new_arr2=np.append(arr2, newarr, axis=1)

In [61]:
print(type(new_arr2))

<class 'numpy.ndarray'>


In [62]:
print(new_arr2)

[[  0 385 171 318 409   4]
 [  1 379 421 410 353   4]
 [  2 162 380  13 394   4]
 ...
 [433  73  38 427 265   4]
 [434 202 236  36 213   4]
 [435  39 239 329  95   4]]


In [63]:
print(new_arr2[0])

[  0 385 171 318 409   4]


In [64]:
print(type(Y_train))

<class 'pandas.core.series.Series'>


In [65]:
arr2

array([[  0, 385, 171, 318, 409],
       [  1, 379, 421, 410, 353],
       [  2, 162, 380,  13, 394],
       ...,
       [433,  73,  38, 427, 265],
       [434, 202, 236,  36, 213],
       [435,  39, 239, 329,  95]], dtype=int64)

In [66]:
print(new_arr2[0][1],  new_arr2[0][2],  new_arr2[0][3], new_arr2[0][4],new_arr2[0][5])

385 171 318 409 4


In [67]:
# Creating and populating a dictionary
new_dist={}
for i, v in Y_train.iteritems():
    new_dist[i]=v

In [68]:
print(new_dist)

{574: 1, 557: 2, 56: 2, 42: 1, 296: 2, 342: 2, 611: 2, 263: 1, 269: 1, 412: 2, 131: 3, 41: 1, 33: 1, 181: 2, 396: 1, 217: 3, 260: 1, 229: 2, 566: 2, 356: 2, 429: 2, 521: 3, 232: 2, 168: 1, 534: 2, 454: 2, 501: 2, 261: 3, 608: 2, 477: 2, 502: 2, 384: 1, 325: 1, 500: 1, 443: 3, 49: 1, 315: 1, 526: 2, 545: 1, 92: 1, 75: 1, 390: 1, 337: 2, 11: 1, 491: 2, 253: 3, 484: 2, 45: 1, 198: 1, 459: 2, 112: 1, 283: 3, 517: 1, 376: 2, 178: 2, 610: 2, 80: 1, 224: 1, 343: 3, 304: 2, 234: 2, 584: 2, 493: 2, 414: 1, 190: 1, 268: 1, 338: 2, 498: 2, 516: 2, 210: 1, 483: 2, 122: 1, 475: 1, 419: 1, 142: 1, 271: 1, 320: 1, 499: 3, 88: 1, 416: 2, 286: 2, 592: 2, 114: 1, 386: 2, 600: 1, 138: 1, 305: 2, 249: 1, 352: 2, 398: 1, 202: 2, 374: 1, 126: 2, 273: 1, 90: 1, 98: 1, 125: 1, 53: 3, 385: 1, 203: 2, 421: 2, 625: 3, 357: 2, 413: 1, 193: 1, 464: 2, 494: 2, 278: 2, 442: 2, 322: 1, 522: 1, 274: 1, 423: 1, 134: 1, 139: 1, 363: 2, 510: 1, 247: 3, 580: 2, 448: 1, 254: 1, 596: 2, 358: 2, 279: 2, 290: 1, 485: 2, 373: 

In [69]:
# Creating and populating a dictionary
new_dist2={}
s=0
for i, v in Y_train.iteritems():
    new_dist2[s]=v
    s=s+1

In [70]:
print(new_dist2)

{0: 1, 1: 2, 2: 2, 3: 1, 4: 2, 5: 2, 6: 2, 7: 1, 8: 1, 9: 2, 10: 3, 11: 1, 12: 1, 13: 2, 14: 1, 15: 3, 16: 1, 17: 2, 18: 2, 19: 2, 20: 2, 21: 3, 22: 2, 23: 1, 24: 2, 25: 2, 26: 2, 27: 3, 28: 2, 29: 2, 30: 2, 31: 1, 32: 1, 33: 1, 34: 3, 35: 1, 36: 1, 37: 2, 38: 1, 39: 1, 40: 1, 41: 1, 42: 2, 43: 1, 44: 2, 45: 3, 46: 2, 47: 1, 48: 1, 49: 2, 50: 1, 51: 3, 52: 1, 53: 2, 54: 2, 55: 2, 56: 1, 57: 1, 58: 3, 59: 2, 60: 2, 61: 2, 62: 2, 63: 1, 64: 1, 65: 1, 66: 2, 67: 2, 68: 2, 69: 1, 70: 2, 71: 1, 72: 1, 73: 1, 74: 1, 75: 1, 76: 1, 77: 3, 78: 1, 79: 2, 80: 2, 81: 2, 82: 1, 83: 2, 84: 1, 85: 1, 86: 2, 87: 1, 88: 2, 89: 1, 90: 2, 91: 1, 92: 2, 93: 1, 94: 1, 95: 1, 96: 1, 97: 3, 98: 1, 99: 2, 100: 2, 101: 3, 102: 2, 103: 1, 104: 1, 105: 2, 106: 2, 107: 2, 108: 2, 109: 1, 110: 1, 111: 1, 112: 1, 113: 1, 114: 1, 115: 2, 116: 1, 117: 3, 118: 2, 119: 1, 120: 1, 121: 2, 122: 2, 123: 2, 124: 1, 125: 2, 126: 3, 127: 1, 128: 1, 129: 1, 130: 2, 131: 3, 132: 2, 133: 1, 134: 1, 135: 2, 136: 2, 137: 2, 138: 

In [71]:
# Creating and populating a dictionary
new_dist3={}
s=0
for i, v in Y_train.iteritems():
    new_dist3[s]=i
    s=s+1

In [72]:
print(new_dist3)

{0: 574, 1: 557, 2: 56, 3: 42, 4: 296, 5: 342, 6: 611, 7: 263, 8: 269, 9: 412, 10: 131, 11: 41, 12: 33, 13: 181, 14: 396, 15: 217, 16: 260, 17: 229, 18: 566, 19: 356, 20: 429, 21: 521, 22: 232, 23: 168, 24: 534, 25: 454, 26: 501, 27: 261, 28: 608, 29: 477, 30: 502, 31: 384, 32: 325, 33: 500, 34: 443, 35: 49, 36: 315, 37: 526, 38: 545, 39: 92, 40: 75, 41: 390, 42: 337, 43: 11, 44: 491, 45: 253, 46: 484, 47: 45, 48: 198, 49: 459, 50: 112, 51: 283, 52: 517, 53: 376, 54: 178, 55: 610, 56: 80, 57: 224, 58: 343, 59: 304, 60: 234, 61: 584, 62: 493, 63: 414, 64: 190, 65: 268, 66: 338, 67: 498, 68: 516, 69: 210, 70: 483, 71: 122, 72: 475, 73: 419, 74: 142, 75: 271, 76: 320, 77: 499, 78: 88, 79: 416, 80: 286, 81: 592, 82: 114, 83: 386, 84: 600, 85: 138, 86: 305, 87: 249, 88: 352, 89: 398, 90: 202, 91: 374, 92: 126, 93: 273, 94: 90, 95: 98, 96: 125, 97: 53, 98: 385, 99: 203, 100: 421, 101: 625, 102: 357, 103: 413, 104: 193, 105: 464, 106: 494, 107: 278, 108: 442, 109: 322, 110: 522, 111: 274, 112

In [73]:
#print(new_dist[204])

In [74]:
    neigh_count=[]
    s=0
    for i, v in new_dist2.items():
        c1=0
        c2=0
        c3=0
        if int(v) == 1:
            c1=c1+1
        elif int(v) == 2:
            c2=c2+1
        else:
            c3=c3+1
        for x in range(1,5):
            if new_dist2[new_arr2[i][x]]==1:
                c1=c1+1
            elif new_dist2[new_arr2[i][x]]==2:
                c2=c2+1
            else:
                c3=c3+1
        print(i," ",new_dist3[i]," ",c1," ",c2," ",c3," ",new_arr2[i][5])
    #real_new=new_dist3[i]," ",new_arr2[i][1]," ",new_arr2[i][2]," ",new_arr2[i][3]," ",new_arr2[i][4]," ",new_arr2[i][5]
    
    #print(i," ",real_new)

0   574   5   0   0   4
1   557   0   5   0   4
2   56   0   4   1   4
3   42   5   0   0   4
4   296   2   3   0   5
5   342   0   5   0   4
6   611   0   5   0   4
7   263   5   0   0   4
8   269   5   0   0   4
9   412   0   4   1   4
10   131   0   2   3   5
11   41   5   0   0   4
12   33   5   0   0   4
13   181   0   5   0   4
14   396   5   0   0   4
15   217   0   2   3   5
16   260   5   0   0   4
17   229   0   5   0   4
18   566   0   5   0   4
19   356   0   5   0   4
20   429   0   5   0   4
21   521   0   3   2   6
22   232   0   5   0   4
23   168   5   0   0   4
24   534   0   4   1   4
25   454   0   5   0   4
26   501   0   5   0   4
27   261   0   2   3   5
28   608   0   5   0   4
29   477   0   5   0   4
30   502   0   5   0   4
31   384   5   0   0   4
32   325   5   0   0   4
33   500   5   0   0   5
34   443   0   1   4   5
35   49   5   0   0   4
36   315   5   0   0   4
37   526   0   5   0   4
38   545   5   0   0   4
39   92   5   0   0   4
40   75   5   0 

432   370   5   0   0   5
433   544   5   0   0   4
434   314   5   0   0   4
435   93   5   0   0   4


In [75]:
#neigh_count=[]
#s=0
#for i, v in new_dist.items():
#    c1=0
#    c2=0
 #   c3=0
  #  if int(v) == 1:
   #     c1=c1+1
    #elif int(v) == 2:
     #   c2=c2+1
    #else:
     #   c3=c3+1
    #for x in range(1,5):
        #print(x)
     #   y=new_dist[new_arr2[s][x]]
      #  print(y)
    #s=s+1
        
            
    
#print(i," ",c1," ",c2," ",c3)
    