In [1]:
import numpy as np 
import pandas as pd 
import math
import random

In [2]:
data=pd.read_csv("new-thyroid.csv")

In [3]:
data.columns=["id","Class","Oxin","Onine","Hormone","Tsh","Resin"]

In [4]:
data.set_index("id", inplace=True)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 214 entries, 2 to 215
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Class    214 non-null    int64  
 1   Oxin     214 non-null    int64  
 2   Onine    214 non-null    float64
 3   Hormone  214 non-null    float64
 4   Tsh      214 non-null    float64
 5   Resin    214 non-null    float64
dtypes: float64(4), int64(2)
memory usage: 11.7 KB


In [6]:
from sklearn.model_selection import train_test_split

In [7]:
data

,Class,Oxin,Onine,Hormone,Tsh,Resin
id,,,,,,
2,1,113,9.9,3.1,2.0,5.9
3,1,127,12.9,2.4,1.4,0.6
4,1,109,5.3,1.6,1.4,1.5
5,1,105,7.3,1.5,1.5,-0.1
6,1,105,6.1,2.1,1.4,7.0
...,...,...,...,...,...,...
211,3,118,6.5,1.3,1.7,11.5
212,3,139,4.2,0.7,4.3,6.3
213,3,103,5.1,1.4,1.2,5.0


In [8]:
X_train, X_test, Y_train, Y_test = train_test_split(data, data.Class, train_size=.7)

In [9]:
train_file_x=X_train.to_csv("xxx.csv")

In [10]:
test_file_x=X_test.to_csv("xx_test.csv")

In [11]:
train_file_y=Y_train.to_csv("yyy.csv")

In [12]:
test_file_y=Y_test.to_csv("yy_test.csv")

In [13]:
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(149, 6) (65, 6) (149,) (65,)


In [14]:
X_train

,Class,Oxin,Onine,Hormone,Tsh,Resin
id,,,,,,
129,1,130,10.0,1.6,0.9,4.6
86,1,107,13.0,1.5,2.8,1.7
10,1,107,13.0,1.1,0.9,3.1
14,1,112,8.1,1.9,3.7,2.0
15,1,122,9.7,1.6,0.9,2.2
...,...,...,...,...,...,...
93,1,112,9.5,2.0,1.2,0.7
111,1,116,16.1,0.9,1.3,1.5
83,1,103,8.5,1.8,1.9,1.1


In [15]:
Y_train

id
129    1
86     1
10     1
14     1
15     1
      ..
93     1
111    1
83     1
21     1
181    2
Name: Class, Length: 149, dtype: int64

In [16]:
gb=X_train.groupby("Class")

In [17]:
for Class, Class_df in gb:
    print(Class)
    print(Class_df)

1
     Class  Oxin  Onine  Hormone  Tsh  Resin
id                                          
129      1   130   10.0      1.6  0.9    4.6
86       1   107   13.0      1.5  2.8    1.7
10       1   107   13.0      1.1  0.9    3.1
14       1   112    8.1      1.9  3.7    2.0
15       1   122    9.7      1.6  0.9    2.2
..     ...   ...    ...      ...  ...    ...
22       1   103   10.1      1.3  0.7    0.1
93       1   112    9.5      2.0  1.2    0.7
111      1   116   16.1      0.9  1.3    1.5
83       1   103    8.5      1.8  1.9    1.1
21       1   101    7.8      1.2  1.0    1.7

[109 rows x 6 columns]
2
     Class  Oxin  Onine  Hormone  Tsh  Resin
id                                          
183      2   106   13.4      3.0  1.1    0.0
185      2    92   11.1      2.0  0.7   -0.2
158      2   110   20.3      3.7  0.6    0.2
163      2    88   12.9      2.7  0.1    0.2
184      2    79   19.0      5.5  0.9    0.3
161      2    89   14.3      4.1  0.5    0.2
168      2    89   21.8    

In [18]:
gb.get_group(1)

,Class,Oxin,Onine,Hormone,Tsh,Resin
id,,,,,,
129,1,130,10.0,1.6,0.9,4.6
86,1,107,13.0,1.5,2.8,1.7
10,1,107,13.0,1.1,0.9,3.1
14,1,112,8.1,1.9,3.7,2.0
15,1,122,9.7,1.6,0.9,2.2
...,...,...,...,...,...,...
22,1,103,10.1,1.3,0.7,0.1
93,1,112,9.5,2.0,1.2,0.7
111,1,116,16.1,0.9,1.3,1.5


In [19]:
class_samples=gb.get_group(1).sample(n=15)
#    print(class_samples)

In [20]:
print(type(class_samples))

<class 'pandas.core.frame.DataFrame'>


In [21]:
mean_sum=class_samples["Oxin"].mean() + class_samples["Onine"].mean() + class_samples["Hormone"].mean() + class_samples["Tsh"].mean() + class_samples["Resin"].mean()

In [22]:
column_length=len(X_train.columns) -1

In [23]:
similar_val_1=mean_sum/column_length
print(similar_val_1)

24.985333333333337


In [24]:
class_2_samples=gb.get_group(2).sample(n=15)
#    print(class_2_samples)

In [25]:
mean_sum_2=class_2_samples["Oxin"].mean() + class_2_samples["Onine"].mean() + class_2_samples["Hormone"].mean() + class_2_samples["Tsh"].mean() + class_2_samples["Resin"].mean()

In [26]:
similar_val_2=mean_sum_2/column_length
print(similar_val_2)

23.522666666666666


In [27]:
class_3_samples=gb.get_group(3).sample(n=15)
#    print(class_3_samples)

In [28]:
mean_sum_3=class_3_samples["Oxin"].mean() + class_3_samples["Onine"].mean() + class_3_samples["Hormone"].mean() + class_3_samples["Tsh"].mean() + class_3_samples["Resin"].mean()

In [29]:
similar_val_3=mean_sum_3/column_length
print(similar_val_3)

32.501333333333335


In [30]:
sim_23=similar_val_3 - similar_val_2
sim_23=sim_23/10
sim_23=1 - sim_23
sim_12=similar_val_1 - similar_val_2
sim_12=sim_12/10
sim_12=1 - sim_12
sim_13=similar_val_3 - similar_val_1
sim_13=sim_13/10
sim_13=1 - sim_13

print("Similarity between 2 and 3: ", sim_23)
print("Similarity between 2 and 1: ", sim_12)
print("Similarity between 1 and 3: ", sim_13)

Similarity between 2 and 3:  0.10213333333333308
Similarity between 2 and 1:  0.8537333333333329
Similarity between 1 and 3:  0.24840000000000018


In [31]:
gb.size()

Class
1    109
2     22
3     18
dtype: int64

In [32]:
m=math.ceil((103+24)/2)

In [33]:
print(m)

64


In [34]:
len(gb)

3

In [35]:
 from sklearn.neighbors import KNeighborsClassifier

In [36]:
neigh = KNeighborsClassifier(n_neighbors=5)

In [37]:
#neigh.fit(X_train, Y_train)
neigh.fit(X_train, X_train.Class)

KNeighborsClassifier()

In [38]:
result=neigh.kneighbors(X_train, return_distance=True)

In [39]:
print(type(result))

<class 'tuple'>


In [40]:
print(result)

(array([[ 0.        ,  1.57162336,  2.66833281,  4.14969878,  4.17971291],
       [ 0.        ,  1.97989899,  2.39374184,  2.60768096,  2.64952826],
       [ 0.        ,  1.5       ,  2.39374184,  2.96479342,  3.06757233],
       [ 0.        ,  2.87402157,  2.95127091,  3.14801525,  3.25269119],
       [ 0.        ,  1.56524758,  2.22261108,  2.39582971,  3.53128872],
       [ 0.        ,  1.3       ,  1.91833261,  2.02731349,  2.20227155],
       [ 0.        ,  1.73493516,  2.10475652,  2.21359436,  2.51396102],
       [ 0.        ,  5.30094331, 13.08166656, 14.6116392 , 27.55340269],
       [ 0.        ,  2.37065392,  2.54165301,  2.64952826,  2.66082694],
       [ 0.        ,  1.396424  ,  1.40712473,  1.47648231,  1.77482393],
       [ 0.        ,  4.6141088 , 10.95810203, 14.16015537, 14.6116392 ],
       [ 0.        ,  1.74642492,  2.80891438,  2.83372546,  3.04959014],
       [ 0.        ,  2.2737634 ,  2.48596058,  2.87402157,  3.10644491],
       [ 0.        ,  1.61864141,  1.

In [41]:
arr1=result[0]

In [42]:
print(type(arr1))

<class 'numpy.ndarray'>


In [43]:
print(arr1.ndim)

2


In [44]:
arr2=result[1]

In [45]:
print(type(arr2))

<class 'numpy.ndarray'>


In [46]:
print(arr1.ndim)

2


In [47]:
print(arr2)

[[  0  70  85  49  33]
 [  1 113   2  74  23]
 [  2 113   1  53 110]
 [  3  12 128 144  77]
 [  4  42  84  24  94]
 [  5 105  44  77  99]
 [  6  77 105   5 144]
 [  7 101  48  10  30]
 [  8  13  78  38 137]
 [  9 111 147  90  87]
 [ 10  48 101  30   7]
 [ 11 126  53 113  29]
 [ 12 128  15   3   6]
 [ 13  78  38   8 137]
 [ 14 132 108 124 128]
 [ 15  86 119  12  73]
 [ 16  81  96  50 133]
 [ 17  91 122  39  43]
 [ 18 124 110  71  73]
 [ 19 140  67  64 113]
 [ 20  80  57  51  93]
 [ 21  89 115  87 112]
 [ 22  34 132  14 108]
 [ 23  74 129   1 110]
 [ 24  84   4  61  42]
 [ 25  82  46  69  26]
 [ 26 109 120 117  55]
 [ 27  65  63  90 136]
 [ 28 144 130 129  77]
 [ 29  37  53  36  31]
 [ 30  50 107  10  96]
 [ 31  36  68  71  53]
 [ 32 130  57  13  77]
 [ 33  49  85 138 133]
 [ 34  22 132  75 108]
 [ 35 132 125 124  75]
 [ 36  31  68  71  53]
 [ 37  29  53  31  36]
 [ 38  78  13   8 137]
 [ 39  43 148  17 122]
 [ 40 116 127  68  92]
 [ 41 121 104 148 118]
 [ 42   4  84 109  24]
 [ 43  39 1

In [48]:
print(arr1)

[[ 0.          1.57162336  2.66833281  4.14969878  4.17971291]
 [ 0.          1.97989899  2.39374184  2.60768096  2.64952826]
 [ 0.          1.5         2.39374184  2.96479342  3.06757233]
 [ 0.          2.87402157  2.95127091  3.14801525  3.25269119]
 [ 0.          1.56524758  2.22261108  2.39582971  3.53128872]
 [ 0.          1.3         1.91833261  2.02731349  2.20227155]
 [ 0.          1.73493516  2.10475652  2.21359436  2.51396102]
 [ 0.          5.30094331 13.08166656 14.6116392  27.55340269]
 [ 0.          2.37065392  2.54165301  2.64952826  2.66082694]
 [ 0.          1.396424    1.40712473  1.47648231  1.77482393]
 [ 0.          4.6141088  10.95810203 14.16015537 14.6116392 ]
 [ 0.          1.74642492  2.80891438  2.83372546  3.04959014]
 [ 0.          2.2737634   2.48596058  2.87402157  3.10644491]
 [ 0.          1.61864141  1.98494332  2.37065392  2.81780056]
 [ 0.          1.92613603  2.00499377  2.21585198  2.36008474]
 [ 0.          1.72336879  2.07364414  2.48596058  2.88

In [49]:
#print(arr1)

In [50]:
print(arr1.size)

745


In [51]:
addVal=[]
s=1
for i in arr1:
    _sum=int(i[0] + i[1] + i[2] + i[3] + i[4])
    addVal.append(_sum)
    print(i ," ", _sum, " ") 
    s=s+1

[0.         1.57162336 2.66833281 4.14969878 4.17971291]   12  
[0.         1.97989899 2.39374184 2.60768096 2.64952826]   9  
[0.         1.5        2.39374184 2.96479342 3.06757233]   9  
[0.         2.87402157 2.95127091 3.14801525 3.25269119]   12  
[0.         1.56524758 2.22261108 2.39582971 3.53128872]   9  
[0.         1.3        1.91833261 2.02731349 2.20227155]   7  
[0.         1.73493516 2.10475652 2.21359436 2.51396102]   8  
[ 0.          5.30094331 13.08166656 14.6116392  27.55340269]   60  
[0.         2.37065392 2.54165301 2.64952826 2.66082694]   10  
[0.         1.396424   1.40712473 1.47648231 1.77482393]   6  
[ 0.          4.6141088  10.95810203 14.16015537 14.6116392 ]   44  
[0.         1.74642492 2.80891438 2.83372546 3.04959014]   10  
[0.         2.2737634  2.48596058 2.87402157 3.10644491]   10  
[0.         1.61864141 1.98494332 2.37065392 2.81780056]   8  
[0.         1.92613603 2.00499377 2.21585198 2.36008474]   8  
[0.         1.72336879 2.07364414 2.48

In [52]:
print(len(addVal))

149


In [53]:
print(addVal)

[12, 9, 9, 12, 9, 7, 8, 60, 10, 6, 44, 10, 10, 8, 8, 9, 56, 17, 8, 22, 6, 9, 9, 10, 10, 22, 11, 10, 10, 5, 49, 6, 9, 12, 12, 8, 6, 6, 9, 16, 7, 31, 9, 16, 7, 20, 25, 28, 43, 11, 35, 7, 16, 6, 7, 10, 10, 6, 11, 10, 9, 9, 20, 6, 12, 7, 18, 14, 6, 11, 12, 7, 8, 8, 8, 6, 17, 7, 7, 9, 6, 69, 24, 38, 7, 12, 9, 9, 20, 10, 6, 13, 9, 6, 13, 19, 62, 7, 63, 7, 11, 49, 15, 7, 23, 7, 13, 33, 6, 8, 8, 7, 12, 9, 91, 9, 8, 7, 18, 9, 10, 19, 16, 63, 7, 7, 9, 9, 8, 9, 8, 10, 5, 16, 71, 130, 13, 7, 18, 8, 12, 14, 13, 9, 8, 19, 7, 6, 15]


In [54]:
arr3=np.array(addVal)

In [55]:
print(type(arr3))

<class 'numpy.ndarray'>


In [56]:
print(arr3.size)

149


In [57]:
print(arr3)

[ 12   9   9  12   9   7   8  60  10   6  44  10  10   8   8   9  56  17
   8  22   6   9   9  10  10  22  11  10  10   5  49   6   9  12  12   8
   6   6   9  16   7  31   9  16   7  20  25  28  43  11  35   7  16   6
   7  10  10   6  11  10   9   9  20   6  12   7  18  14   6  11  12   7
   8   8   8   6  17   7   7   9   6  69  24  38   7  12   9   9  20  10
   6  13   9   6  13  19  62   7  63   7  11  49  15   7  23   7  13  33
   6   8   8   7  12   9  91   9   8   7  18   9  10  19  16  63   7   7
   9   9   8   9   8  10   5  16  71 130  13   7  18   8  12  14  13   9
   8  19   7   6  15]


In [58]:
g=1
for i in addVal:
    print(g ," ", i) 
    g=g+1

1   12
2   9
3   9
4   12
5   9
6   7
7   8
8   60
9   10
10   6
11   44
12   10
13   10
14   8
15   8
16   9
17   56
18   17
19   8
20   22
21   6
22   9
23   9
24   10
25   10
26   22
27   11
28   10
29   10
30   5
31   49
32   6
33   9
34   12
35   12
36   8
37   6
38   6
39   9
40   16
41   7
42   31
43   9
44   16
45   7
46   20
47   25
48   28
49   43
50   11
51   35
52   7
53   16
54   6
55   7
56   10
57   10
58   6
59   11
60   10
61   9
62   9
63   20
64   6
65   12
66   7
67   18
68   14
69   6
70   11
71   12
72   7
73   8
74   8
75   8
76   6
77   17
78   7
79   7
80   9
81   6
82   69
83   24
84   38
85   7
86   12
87   9
88   9
89   20
90   10
91   6
92   13
93   9
94   6
95   13
96   19
97   62
98   7
99   63
100   7
101   11
102   49
103   15
104   7
105   23
106   7
107   13
108   33
109   6
110   8
111   8
112   7
113   12
114   9
115   91
116   9
117   8
118   7
119   18
120   9
121   10
122   19
123   16
124   63
125   7
126   7
127   9
128   9
129   8
130   9
131 

In [59]:
newarr = arr3.reshape(149, 1)

In [60]:
print(newarr.ndim)

2


In [61]:
new_arr2=np.append(arr2, newarr, axis=1)

In [62]:
print(type(new_arr2))

<class 'numpy.ndarray'>


In [63]:
print(new_arr2)

[[  0  70  85  49  33  12]
 [  1 113   2  74  23   9]
 [  2 113   1  53 110   9]
 [  3  12 128 144  77  12]
 [  4  42  84  24  94   9]
 [  5 105  44  77  99   7]
 [  6  77 105   5 144   8]
 [  7 101  48  10  30  60]
 [  8  13  78  38 137  10]
 [  9 111 147  90  87   6]
 [ 10  48 101  30   7  44]
 [ 11 126  53 113  29  10]
 [ 12 128  15   3   6  10]
 [ 13  78  38   8 137   8]
 [ 14 132 108 124 128   8]
 [ 15  86 119  12  73   9]
 [ 16  81  96  50 133  56]
 [ 17  91 122  39  43  17]
 [ 18 124 110  71  73   8]
 [ 19 140  67  64 113  22]
 [ 20  80  57  51  93   6]
 [ 21  89 115  87 112   9]
 [ 22  34 132  14 108   9]
 [ 23  74 129   1 110  10]
 [ 24  84   4  61  42  10]
 [ 25  82  46  69  26  22]
 [ 26 109 120 117  55  11]
 [ 27  65  63  90 136  10]
 [ 28 144 130 129  77  10]
 [ 29  37  53  36  31   5]
 [ 30  50 107  10  96  49]
 [ 31  36  68  71  53   6]
 [ 32 130  57  13  77   9]
 [ 33  49  85 138 133  12]
 [ 34  22 132  75 108  12]
 [ 35 132 125 124  75   8]
 [ 36  31  68  71  53   6]
 

In [64]:
print(new_arr2[0])

[ 0 70 85 49 33 12]


In [65]:
print(type(Y_train))

<class 'pandas.core.series.Series'>


In [66]:
arr2

array([[  0,  70,  85,  49,  33],
       [  1, 113,   2,  74,  23],
       [  2, 113,   1,  53, 110],
       [  3,  12, 128, 144,  77],
       [  4,  42,  84,  24,  94],
       [  5, 105,  44,  77,  99],
       [  6,  77, 105,   5, 144],
       [  7, 101,  48,  10,  30],
       [  8,  13,  78,  38, 137],
       [  9, 111, 147,  90,  87],
       [ 10,  48, 101,  30,   7],
       [ 11, 126,  53, 113,  29],
       [ 12, 128,  15,   3,   6],
       [ 13,  78,  38,   8, 137],
       [ 14, 132, 108, 124, 128],
       [ 15,  86, 119,  12,  73],
       [ 16,  81,  96,  50, 133],
       [ 17,  91, 122,  39,  43],
       [ 18, 124, 110,  71,  73],
       [ 19, 140,  67,  64, 113],
       [ 20,  80,  57,  51,  93],
       [ 21,  89, 115,  87, 112],
       [ 22,  34, 132,  14, 108],
       [ 23,  74, 129,   1, 110],
       [ 24,  84,   4,  61,  42],
       [ 25,  82,  46,  69,  26],
       [ 26, 109, 120, 117,  55],
       [ 27,  65,  63,  90, 136],
       [ 28, 144, 130, 129,  77],
       [ 29,  

In [67]:
print(new_arr2[0][1],  new_arr2[0][2],  new_arr2[0][3], new_arr2[0][4],new_arr2[0][5])

70 85 49 33 12


In [68]:
# Creating and populating a dictionary
new_dist={}
for i, v in Y_train.iteritems():
    new_dist[i]=v

In [69]:
print(new_dist)

{129: 1, 86: 1, 10: 1, 14: 1, 15: 1, 53: 1, 106: 1, 199: 3, 8: 1, 127: 1, 187: 3, 183: 2, 92: 1, 128: 1, 114: 1, 131: 1, 186: 3, 185: 2, 101: 1, 158: 2, 32: 1, 70: 1, 33: 1, 95: 1, 25: 1, 211: 3, 99: 1, 26: 1, 134: 1, 29: 1, 206: 3, 38: 1, 103: 1, 146: 1, 120: 1, 47: 1, 27: 1, 107: 1, 109: 1, 163: 2, 5: 1, 184: 2, 41: 1, 161: 2, 137: 1, 168: 2, 197: 3, 157: 2, 210: 3, 74: 1, 205: 3, 28: 1, 182: 2, 59: 1, 126: 1, 135: 1, 84: 1, 63: 1, 11: 1, 40: 1, 49: 1, 87: 1, 189: 3, 78: 1, 178: 2, 125: 1, 82: 1, 153: 2, 116: 1, 65: 1, 39: 1, 46: 1, 12: 1, 113: 1, 100: 1, 124: 1, 94: 1, 96: 1, 64: 1, 51: 1, 36: 1, 190: 3, 50: 1, 151: 2, 58: 1, 43: 1, 4: 1, 61: 1, 174: 2, 104: 1, 24: 1, 57: 1, 121: 1, 112: 1, 45: 1, 73: 1, 207: 3, 67: 1, 154: 2, 18: 1, 77: 1, 193: 3, 71: 1, 55: 1, 172: 2, 20: 1, 166: 2, 203: 3, 119: 1, 54: 1, 79: 1, 110: 1, 213: 3, 108: 1, 208: 3, 66: 1, 89: 1, 123: 1, 165: 2, 139: 1, 48: 1, 173: 2, 34: 1, 156: 2, 16: 1, 7: 1, 180: 2, 141: 1, 118: 1, 23: 1, 69: 1, 122: 1, 60: 1, 138: 

In [70]:
# Creating and populating a dictionary
new_dist2={}
s=0
for i, v in Y_train.iteritems():
    new_dist2[s]=v
    s=s+1

In [71]:
print(new_dist2)

{0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 3, 8: 1, 9: 1, 10: 3, 11: 2, 12: 1, 13: 1, 14: 1, 15: 1, 16: 3, 17: 2, 18: 1, 19: 2, 20: 1, 21: 1, 22: 1, 23: 1, 24: 1, 25: 3, 26: 1, 27: 1, 28: 1, 29: 1, 30: 3, 31: 1, 32: 1, 33: 1, 34: 1, 35: 1, 36: 1, 37: 1, 38: 1, 39: 2, 40: 1, 41: 2, 42: 1, 43: 2, 44: 1, 45: 2, 46: 3, 47: 2, 48: 3, 49: 1, 50: 3, 51: 1, 52: 2, 53: 1, 54: 1, 55: 1, 56: 1, 57: 1, 58: 1, 59: 1, 60: 1, 61: 1, 62: 3, 63: 1, 64: 2, 65: 1, 66: 1, 67: 2, 68: 1, 69: 1, 70: 1, 71: 1, 72: 1, 73: 1, 74: 1, 75: 1, 76: 1, 77: 1, 78: 1, 79: 1, 80: 1, 81: 3, 82: 1, 83: 2, 84: 1, 85: 1, 86: 1, 87: 1, 88: 2, 89: 1, 90: 1, 91: 1, 92: 1, 93: 1, 94: 1, 95: 1, 96: 3, 97: 1, 98: 2, 99: 1, 100: 1, 101: 3, 102: 1, 103: 1, 104: 2, 105: 1, 106: 2, 107: 3, 108: 1, 109: 1, 110: 1, 111: 1, 112: 3, 113: 1, 114: 3, 115: 1, 116: 1, 117: 1, 118: 2, 119: 1, 120: 1, 121: 2, 122: 1, 123: 2, 124: 1, 125: 1, 126: 2, 127: 1, 128: 1, 129: 1, 130: 1, 131: 1, 132: 1, 133: 1, 134: 3, 135: 3, 136: 1, 137: 1, 138: 

In [72]:
# Creating and populating a dictionary
new_dist3={}
s=0
for i, v in Y_train.iteritems():
    new_dist3[s]=i
    s=s+1

In [73]:
print(new_dist3)

{0: 129, 1: 86, 2: 10, 3: 14, 4: 15, 5: 53, 6: 106, 7: 199, 8: 8, 9: 127, 10: 187, 11: 183, 12: 92, 13: 128, 14: 114, 15: 131, 16: 186, 17: 185, 18: 101, 19: 158, 20: 32, 21: 70, 22: 33, 23: 95, 24: 25, 25: 211, 26: 99, 27: 26, 28: 134, 29: 29, 30: 206, 31: 38, 32: 103, 33: 146, 34: 120, 35: 47, 36: 27, 37: 107, 38: 109, 39: 163, 40: 5, 41: 184, 42: 41, 43: 161, 44: 137, 45: 168, 46: 197, 47: 157, 48: 210, 49: 74, 50: 205, 51: 28, 52: 182, 53: 59, 54: 126, 55: 135, 56: 84, 57: 63, 58: 11, 59: 40, 60: 49, 61: 87, 62: 189, 63: 78, 64: 178, 65: 125, 66: 82, 67: 153, 68: 116, 69: 65, 70: 39, 71: 46, 72: 12, 73: 113, 74: 100, 75: 124, 76: 94, 77: 96, 78: 64, 79: 51, 80: 36, 81: 190, 82: 50, 83: 151, 84: 58, 85: 43, 86: 4, 87: 61, 88: 174, 89: 104, 90: 24, 91: 57, 92: 121, 93: 112, 94: 45, 95: 73, 96: 207, 97: 67, 98: 154, 99: 18, 100: 77, 101: 193, 102: 71, 103: 55, 104: 172, 105: 20, 106: 166, 107: 203, 108: 119, 109: 54, 110: 79, 111: 110, 112: 213, 113: 108, 114: 208, 115: 66, 116: 89, 1

In [74]:
#print(new_dist[204])

<!-- Populating a dictionary  -->

In [75]:
    neigh_count=[]
    s=0
    for i, v in new_dist2.items():
        c1=0
        c2=0
        c3=0
        class_example=0
        if int(v) == 1:
            c1=c1+1
        elif int(v) == 2:
            c2=c2+1
        else:
            c3=c3+1
        for x in range(1,5):
            if new_dist2[new_arr2[i][x]]==1:
                c1=c1+1
            elif new_dist2[new_arr2[i][x]]==2:
                c2=c2+1
            else:
                c3=c3+1
            if int(v) == 1:
                safe_level=(1 * c1 + sim_12 * c2 + sim_13 * c3)/5
                class_example=1
                safe_level=round(safe_level,2)
            elif int(v) == 2:
                safe_level=(sim_12 * c1 + 1 * c2 + sim_23 * c3)/5
                class_example=2
                safe_level=round(safe_level,2)
            else:
                safe_level=(sim_13 * c1 + sim_23 * c2 + 1 * c3)/5
                class_example=3
                safe_level=round(safe_level,2)
        neigh_count.append([i,new_dist3[i],class_example,c1,c2,c3,safe_level,new_arr2[i][5]])
        #print(i," ",new_dist3[i]," ",class_example," ",c1," ",c2," ",c3," ",safe_level," ",new_arr2[i][5])
        #print(i," ",new_dist3[i]," ",c1," ",c2," ",c3," ",new_arr2[i][5])
    #real_new=new_dist3[i]," ",new_arr2[i][1]," ",new_arr2[i][2]," ",new_arr2[i][3]," ",new_arr2[i][4]," ",new_arr2[i][5]
    
    #print(i," ",real_new)

In [76]:
#print(neigh_count)

In [77]:
# iterating a dictionary

In [78]:
# for s in range(149):
#     print(neigh_count[s])

In [79]:
# Converting a dictionary to a dataframe

In [80]:
new_main_df = pd.DataFrame(neigh_count,columns=['s_no','real_index','Class','c_one','c_two','c_three','safe_level','distance'])

In [81]:
#print(new_main_df)

In [82]:
new_main_df.set_index("s_no", inplace=True)

In [83]:
print(new_main_df)

      real_index  Class  c_one  c_two  c_three  safe_level  distance
s_no                                                                
0            129      1      5      0        0        1.00        12
1             86      1      5      0        0        1.00         9
2             10      1      5      0        0        1.00         9
3             14      1      5      0        0        1.00        12
4             15      1      5      0        0        1.00         9
...          ...    ...    ...    ...      ...         ...       ...
144           93      1      5      0        0        1.00         8
145          111      1      4      1        0        0.97        19
146           83      1      5      0        0        1.00         7
147           21      1      5      0        0        1.00         6
148          181      2      0      5        0        1.00        15

[149 rows x 7 columns]


In [84]:
# iterating through a dataframe, the following methods can be used .iterrows() 
# and itertuples() but itertuples is preferred because it keeps the data types and more

In [85]:
# for index, row in new_main_df.iterrows():
#     print(index, row['real_index'], row['class'], row['c_one'], row['c_two'], row['c_three'], row['safe_level'], row['distance'] )

In [86]:
for i, row in enumerate(new_main_df.itertuples(), 0):
    print(i, row.real_index)
    

0 129
1 86
2 10
3 14
4 15
5 53
6 106
7 199
8 8
9 127
10 187
11 183
12 92
13 128
14 114
15 131
16 186
17 185
18 101
19 158
20 32
21 70
22 33
23 95
24 25
25 211
26 99
27 26
28 134
29 29
30 206
31 38
32 103
33 146
34 120
35 47
36 27
37 107
38 109
39 163
40 5
41 184
42 41
43 161
44 137
45 168
46 197
47 157
48 210
49 74
50 205
51 28
52 182
53 59
54 126
55 135
56 84
57 63
58 11
59 40
60 49
61 87
62 189
63 78
64 178
65 125
66 82
67 153
68 116
69 65
70 39
71 46
72 12
73 113
74 100
75 124
76 94
77 96
78 64
79 51
80 36
81 190
82 50
83 151
84 58
85 43
86 4
87 61
88 174
89 104
90 24
91 57
92 121
93 112
94 45
95 73
96 207
97 67
98 154
99 18
100 77
101 193
102 71
103 55
104 172
105 20
106 166
107 203
108 119
109 54
110 79
111 110
112 213
113 108
114 208
115 66
116 89
117 123
118 165
119 139
120 48
121 173
122 34
123 156
124 16
125 7
126 180
127 141
128 118
129 23
130 69
131 122
132 60
133 138
134 191
135 195
136 142
137 13
138 3
139 147
140 152
141 215
142 6
143 22
144 93
145 111
146 83
147 21
148 1

In [87]:
# for row in new_main_df.itertuples():
#     print(getattr(row, 'real_index'), getattr(row, 'c_one'))

In [88]:
new_gb=new_main_df.groupby("Class")

In [89]:
new_1=new_gb.get_group(1).sort_values(['safe_level', 'distance'], ascending=[False, False])

In [90]:
#new_1

In [91]:
#new_2=new_gb.get_group(2)

In [92]:
#new_3=new_gb.get_group(3)

In [93]:
gb_1=gb.get_group(1)

In [94]:
gb_2=gb.get_group(2)

In [95]:
gb_3=gb.get_group(3)

In [96]:
#new_gb.get_group(1).sort_values(['safe_level', 'distance'], ascending=[False, False])

In [97]:
new_2=new_gb.get_group(2).sort_values(['safe_level', 'distance'], ascending=[False, False])

In [98]:
new_2.drop(new_2[new_2['c_two'] < 4].index, inplace=True)

In [99]:
#new_2

In [100]:
#b=len(new_2.index)

In [101]:
#print(b)

In [102]:
#s=m-b

In [103]:
#print(s)

In [104]:
minor_c_2=new_2.sample(n=m, replace='True')
print(minor_c_2)

      real_index  Class  c_one  c_two  c_three  safe_level  distance
s_no                                                                
41           184      2      0      5        0        1.00        31
45           168      2      0      5        0        1.00        20
19           158      2      1      4        0        0.97        22
148          181      2      0      5        0        1.00        15
140          152      2      1      4        0        0.97        12
...          ...    ...    ...    ...      ...         ...       ...
104          172      2      0      5        0        1.00        23
45           168      2      0      5        0        1.00        20
140          152      2      1      4        0        0.97        12
121          173      2      0      5        0        1.00        19
121          173      2      0      5        0        1.00        19

[64 rows x 7 columns]


In [105]:
new_3=new_gb.get_group(3).sort_values(['safe_level', 'distance'], ascending=[False, True])

In [106]:
new_3.drop(new_3[new_3['c_three'] < 4].index, inplace=True)

In [107]:
minor_c_3=new_3.sample(n=m, replace='True')
print(minor_c_3)

      real_index  Class  c_one  c_two  c_three  safe_level  distance
s_no                                                                
96           207      3      0      0        5        1.00        62
48           210      3      0      0        5        1.00        43
30           206      3      0      0        5        1.00        49
16           186      3      1      0        4        0.85        56
135          195      3      0      0        5        1.00       130
...          ...    ...    ...    ...      ...         ...       ...
16           186      3      1      0        4        0.85        56
81           190      3      1      0        4        0.85        69
107          203      3      1      0        4        0.85        33
81           190      3      1      0        4        0.85        69
7            199      3      0      0        5        1.00        60

[64 rows x 7 columns]


In [108]:
new_gb

In [109]:
gb

In [110]:
#new_1

In [111]:
new_1.drop(new_1[new_1['c_one'] < 5].index, inplace=True)

In [112]:
#new_1

In [113]:
#for i, row in enumerate(new_1.itertuples(index=True), 0):
    #print(i, row.Index, row.real_index, row.Class, row.c_one, row.c_two, row.c_three, row.safe_level, row.distance)

In [114]:
#r=len(new_1.index)-m

In [115]:
#print(r)

In [116]:
major_c_1=new_1.sample(n=m)
print(major_c_1)

      real_index  Class  c_one  c_two  c_three  safe_level  distance
s_no                                                                
35            47      1      5      0        0         1.0         8
138            3      1      5      0        0         1.0        18
70            39      1      5      0        0         1.0        12
72            12      1      5      0        0         1.0         8
57            63      1      5      0        0         1.0         6
...          ...    ...    ...    ...      ...         ...       ...
29            29      1      5      0        0         1.0         5
99            18      1      5      0        0         1.0         7
2             10      1      5      0        0         1.0         9
93           112      1      5      0        0         1.0         6
139          147      1      5      0        0         1.0         8

[64 rows x 7 columns]


In [117]:
for i, row in enumerate(major_c_1.itertuples(index=True), 0):
    print(i, row.real_index)

0 47
1 3
2 39
3 12
4 63
5 127
6 134
7 32
8 5
9 64
10 74
11 36
12 96
13 25
14 107
15 87
16 49
17 124
18 71
19 53
20 60
21 142
22 77
23 120
24 129
25 45
26 83
27 15
28 33
29 131
30 89
31 116
32 26
33 48
34 55
35 54
36 99
37 95
38 24
39 122
40 13
41 73
42 141
43 146
44 123
45 59
46 8
47 84
48 135
49 94
50 113
51 40
52 27
53 22
54 69
55 86
56 61
57 38
58 118
59 29
60 18
61 10
62 112
63 147


In [118]:
#how to generate a random list from an interval
#num_list = random.sample(range(0, len(new_1.index)), r)
#print(num_list)

In [119]:
maj_c_filtered=[]
for i, row in enumerate(major_c_1.itertuples(index=True), 0):
    a=gb_1.at[row.real_index, 'Class']
    b=gb_1.at[row.real_index, 'Oxin']
    c=gb_1.at[row.real_index, 'Onine']
    d=gb_1.at[row.real_index, 'Hormone']
    e=gb_1.at[row.real_index, 'Tsh']
    f=gb_1.at[row.real_index, 'Resin']
    maj_c_filtered.append([a,b,c,d,e,f])

In [120]:
print(maj_c_filtered)

[[1, 109, 10.0, 1.3, 1.8, 4.3], [1, 127, 12.9, 2.4, 1.4, 0.6], [1, 130, 9.5, 1.7, 0.4, 3.2], [1, 110, 11.3, 2.3, 0.9, 3.3], [1, 115, 10.4, 1.8, 1.6, 2.0], [1, 102, 8.4, 1.5, 0.8, 2.4], [1, 112, 10.6, 1.6, 0.9, -0.1], [1, 116, 11.1, 2.0, 1.2, 2.3], [1, 105, 7.3, 1.5, 1.5, -0.1], [1, 116, 10.0, 1.7, 1.5, 4.3], [1, 126, 9.4, 2.3, 1.0, 4.0], [1, 117, 11.0, 1.4, 1.5, 2.1], [1, 114, 9.1, 2.6, 1.5, 1.5], [1, 121, 10.1, 1.7, 1.3, 0.1], [1, 105, 11.1, 1.1, 0.8, 1.2], [1, 119, 11.4, 2.3, 2.2, 1.6], [1, 100, 9.5, 2.5, 1.3, -0.2], [1, 111, 9.1, 1.7, 1.2, 4.1], [1, 96, 9.4, 1.5, 1.0, 3.1], [1, 115, 8.1, 1.7, 0.6, 2.2], [1, 110, 8.7, 1.9, 1.6, 4.4], [1, 98, 5.7, 0.4, 1.3, 2.8], [1, 119, 12.9, 1.5, 1.3, 3.6], [1, 111, 8.5, 1.6, 1.2, 7.7], [1, 130, 10.0, 1.6, 0.9, 4.6], [1, 123, 8.1, 2.3, 1.0, 5.1], [1, 103, 8.5, 1.8, 1.9, 1.1], [1, 122, 9.7, 1.6, 0.9, 2.2], [1, 110, 7.8, 1.9, 2.1, 6.4], [1, 110, 6.3, 1.0, 0.8, 1.0], [1, 105, 8.1, 2.0, 1.9, -0.5], [1, 105, 8.7, 1.5, 1.1, 1.5], [1, 100, 6.1, 2.4, 1.8, 

In [121]:
for i, row in enumerate(minor_c_2.itertuples(index=True), 0):
    print(i, row.real_index)

0 184
1 168
2 158
3 181
4 152
5 154
6 163
7 154
8 168
9 173
10 184
11 165
12 168
13 156
14 158
15 181
16 152
17 161
18 163
19 173
20 173
21 165
22 152
23 172
24 165
25 158
26 158
27 163
28 168
29 165
30 173
31 168
32 161
33 154
34 181
35 173
36 152
37 165
38 154
39 181
40 153
41 161
42 156
43 153
44 154
45 173
46 163
47 156
48 154
49 158
50 161
51 158
52 158
53 163
54 168
55 152
56 172
57 181
58 152
59 172
60 168
61 152
62 173
63 173


In [122]:
min_c_2_filtered=[]
for i, row in enumerate(minor_c_2.itertuples(index=True), 0):
    a=gb_2.at[row.real_index, 'Class']
    b=gb_2.at[row.real_index, 'Oxin']
    c=gb_2.at[row.real_index, 'Onine']
    d=gb_2.at[row.real_index, 'Hormone']
    e=gb_2.at[row.real_index, 'Tsh']
    f=gb_2.at[row.real_index, 'Resin']
    min_c_2_filtered.append([a,b,c,d,e,f])

In [123]:
print(min_c_2_filtered)

[[2, 79, 19.0, 5.5, 0.9, 0.3], [2, 89, 21.8, 7.1, 0.7, -0.1], [2, 110, 20.3, 3.7, 0.6, 0.2], [2, 88, 16.5, 4.9, 0.8, 0.1], [2, 111, 16.0, 2.1, 0.9, -0.1], [2, 65, 25.3, 5.8, 1.3, 0.2], [2, 88, 12.9, 2.7, 0.1, 0.2], [2, 65, 25.3, 5.8, 1.3, 0.2], [2, 89, 21.8, 7.1, 0.7, -0.1], [2, 84, 18.5, 4.4, 1.1, -0.3], [2, 79, 19.0, 5.5, 0.9, 0.3], [2, 89, 20.1, 7.3, 1.1, -0.2], [2, 89, 21.8, 7.1, 0.7, -0.1], [2, 65, 18.2, 10.0, 1.3, 0.1], [2, 110, 20.3, 3.7, 0.6, 0.2], [2, 88, 16.5, 4.9, 0.8, 0.1], [2, 111, 16.0, 2.1, 0.9, -0.1], [2, 89, 14.3, 4.1, 0.5, 0.2], [2, 88, 12.9, 2.7, 0.1, 0.2], [2, 84, 18.5, 4.4, 1.1, -0.3], [2, 84, 18.5, 4.4, 1.1, -0.3], [2, 89, 20.1, 7.3, 1.1, -0.2], [2, 111, 16.0, 2.1, 0.9, -0.1], [2, 84, 21.5, 2.7, 1.1, -0.6], [2, 89, 20.1, 7.3, 1.1, -0.2], [2, 110, 20.3, 3.7, 0.6, 0.2], [2, 110, 20.3, 3.7, 0.6, 0.2], [2, 88, 12.9, 2.7, 0.1, 0.2], [2, 89, 21.8, 7.1, 0.7, -0.1], [2, 89, 20.1, 7.3, 1.1, -0.2], [2, 84, 18.5, 4.4, 1.1, -0.3], [2, 89, 21.8, 7.1, 0.7, -0.1], [2, 89, 14.3, 

In [124]:
for i, row in enumerate(minor_c_3.itertuples(index=True), 0):
    print(i, row.real_index)

0 207
1 210
2 206
3 186
4 195
5 193
6 187
7 206
8 210
9 210
10 206
11 187
12 195
13 210
14 210
15 193
16 190
17 193
18 206
19 186
20 193
21 193
22 205
23 210
24 205
25 187
26 206
27 195
28 207
29 203
30 207
31 193
32 186
33 206
34 206
35 190
36 206
37 199
38 187
39 203
40 203
41 187
42 187
43 186
44 195
45 207
46 208
47 195
48 190
49 187
50 186
51 195
52 206
53 186
54 208
55 208
56 210
57 205
58 190
59 186
60 190
61 203
62 190
63 199


In [125]:
min_c_3_filtered=[]
for i, row in enumerate(minor_c_3.itertuples(index=True), 0):
    a=gb_3.at[row.real_index, 'Class']
    b=gb_3.at[row.real_index, 'Oxin']
    c=gb_3.at[row.real_index, 'Onine']
    d=gb_3.at[row.real_index, 'Hormone']
    e=gb_3.at[row.real_index, 'Tsh']
    f=gb_3.at[row.real_index, 'Resin']
    min_c_3_filtered.append([a,b,c,d,e,f])

In [126]:
print(min_c_3_filtered)

[[3, 123, 1.9, 0.3, 22.8, 22.2], [3, 119, 5.1, 1.1, 7.0, 40.8], [3, 125, 3.7, 1.1, 8.5, 25.9], [3, 125, 2.3, 0.9, 16.5, 9.5], [3, 119, 0.8, 0.7, 56.4, 21.6], [3, 118, 3.6, 1.5, 11.6, 48.8], [3, 120, 6.8, 2.1, 10.4, 38.6], [3, 125, 3.7, 1.1, 8.5, 25.9], [3, 119, 5.1, 1.1, 7.0, 40.8], [3, 119, 5.1, 1.1, 7.0, 40.8], [3, 125, 3.7, 1.1, 8.5, 25.9], [3, 120, 6.8, 2.1, 10.4, 38.6], [3, 119, 0.8, 0.7, 56.4, 21.6], [3, 119, 5.1, 1.1, 7.0, 40.8], [3, 119, 5.1, 1.1, 7.0, 40.8], [3, 118, 3.6, 1.5, 11.6, 48.8], [3, 119, 3.8, 1.1, 23.0, 5.7], [3, 118, 3.6, 1.5, 11.6, 48.8], [3, 125, 3.7, 1.1, 8.5, 25.9], [3, 125, 2.3, 0.9, 16.5, 9.5], [3, 118, 3.6, 1.5, 11.6, 48.8], [3, 118, 3.6, 1.5, 11.6, 48.8], [3, 120, 3.4, 1.8, 7.5, 21.5], [3, 119, 5.1, 1.1, 7.0, 40.8], [3, 120, 3.4, 1.8, 7.5, 21.5], [3, 120, 6.8, 2.1, 10.4, 38.6], [3, 125, 3.7, 1.1, 8.5, 25.9], [3, 119, 0.8, 0.7, 56.4, 21.6], [3, 123, 1.9, 0.3, 22.8, 22.2], [3, 113, 5.1, 0.7, 5.8, 19.6], [3, 123, 1.9, 0.3, 22.8, 22.2], [3, 118, 3.6, 1.5, 11.6,

In [127]:
new_min_c_3_filtered = pd.DataFrame(min_c_3_filtered,columns=['Class','Oxin','Onine','Hormone','Tsh','Resin'])

In [128]:
print(new_min_c_3_filtered)

    Class  Oxin  Onine  Hormone   Tsh  Resin
0       3   123    1.9      0.3  22.8   22.2
1       3   119    5.1      1.1   7.0   40.8
2       3   125    3.7      1.1   8.5   25.9
3       3   125    2.3      0.9  16.5    9.5
4       3   119    0.8      0.7  56.4   21.6
..    ...   ...    ...      ...   ...    ...
59      3   125    2.3      0.9  16.5    9.5
60      3   119    3.8      1.1  23.0    5.7
61      3   113    5.1      0.7   5.8   19.6
62      3   119    3.8      1.1  23.0    5.7
63      3   121    4.7      1.8  11.2   53.0

[64 rows x 6 columns]


In [129]:
new_min_c_2_filtered = pd.DataFrame(min_c_2_filtered,columns=['Class','Oxin','Onine','Hormone','Tsh','Resin'])

In [130]:
print(new_min_c_2_filtered)

    Class  Oxin  Onine  Hormone  Tsh  Resin
0       2    79   19.0      5.5  0.9    0.3
1       2    89   21.8      7.1  0.7   -0.1
2       2   110   20.3      3.7  0.6    0.2
3       2    88   16.5      4.9  0.8    0.1
4       2   111   16.0      2.1  0.9   -0.1
..    ...   ...    ...      ...  ...    ...
59      2    84   21.5      2.7  1.1   -0.6
60      2    89   21.8      7.1  0.7   -0.1
61      2   111   16.0      2.1  0.9   -0.1
62      2    84   18.5      4.4  1.1   -0.3
63      2    84   18.5      4.4  1.1   -0.3

[64 rows x 6 columns]


In [131]:
new_maj_c_filtered = pd.DataFrame(maj_c_filtered,columns=['Class','Oxin','Onine','Hormone','Tsh','Resin'])

In [132]:
print(new_maj_c_filtered)

    Class  Oxin  Onine  Hormone  Tsh  Resin
0       1   109   10.0      1.3  1.8    4.3
1       1   127   12.9      2.4  1.4    0.6
2       1   130    9.5      1.7  0.4    3.2
3       1   110   11.3      2.3  0.9    3.3
4       1   115   10.4      1.8  1.6    2.0
..    ...   ...    ...      ...  ...    ...
59      1   105   11.1      2.0  1.0    1.0
60      1   114    6.7      1.5  1.0    3.5
61      1   107   13.0      1.1  0.9    3.1
62      1   118   10.6      1.8  1.4    3.0
63      1   114    7.5      1.1  1.6    4.4

[64 rows x 6 columns]


In [133]:
result = new_maj_c_filtered.append([new_min_c_2_filtered, new_min_c_3_filtered], ignore_index='True')

In [134]:
print(result)

     Class  Oxin  Onine  Hormone   Tsh  Resin
0        1   109   10.0      1.3   1.8    4.3
1        1   127   12.9      2.4   1.4    0.6
2        1   130    9.5      1.7   0.4    3.2
3        1   110   11.3      2.3   0.9    3.3
4        1   115   10.4      1.8   1.6    2.0
..     ...   ...    ...      ...   ...    ...
187      3   125    2.3      0.9  16.5    9.5
188      3   119    3.8      1.1  23.0    5.7
189      3   113    5.1      0.7   5.8   19.6
190      3   119    3.8      1.1  23.0    5.7
191      3   121    4.7      1.8  11.2   53.0

[192 rows x 6 columns]


In [135]:
result.to_csv("balanced_new_thyroid.csv")

In [136]:
result.sample(frac=1).reset_index(drop=True)

,Class,Oxin,Onine,Hormone,Tsh,Resin
0,2,88,16.5,4.9,0.8,0.1
1,1,110,11.3,2.3,0.9,3.3
2,2,110,20.3,3.7,0.6,0.2
3,1,106,9.6,2.4,1.0,1.3
4,2,84,18.5,4.4,1.1,-0.3
...,...,...,...,...,...,...
187,2,65,18.2,10.0,1.3,0.1
188,2,89,21.8,7.1,0.7,-0.1
189,3,113,5.1,0.7,5.8,19.6
190,1,116,11.1,2.0,1.2,2.3


In [137]:
result.to_csv("balanced_new_thyroid_rand.csv")

In [138]:
from sklearn import svm

In [139]:
model=svm.SVC(C = 1)

In [140]:
model.fit(X_train, Y_train)

SVC(C=1)

In [141]:
Y_pred=model.predict(X_test)

In [142]:
print(Y_pred)

[3 3 2 1 1 1 1 1 3 1 1 1 1 1 1 1 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1]


In [143]:
from sklearn import metrics
Y_pred=model.predict(X_train)
print("Accuracy: ", metrics.accuracy_score(Y_train, Y_pred))

Accuracy:  0.7986577181208053
