In [1]:
import numpy as np 
import pandas as pd 
import math
import random
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, cross_val_predict
from sklearn import metrics
from sklearn import svm
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import roc_auc_score
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.dummy import DummyClassifier
from imblearn.metrics import geometric_mean_score

In [2]:
data=pd.read_csv("wine.csv")

In [3]:
import sklearn
sklearn.__version__

'1.0.2'

In [4]:
data

,Unnamed: 0,Class,a,b,c,d,e,f,g,h,i,j,k,l,m
0,0,1,14.38,3.59,2.28,16.0,102,3.25,3.17,0.27,2.19,4.90,1.04,3.44,1065
1,1,1,14.22,3.99,2.51,13.2,128,3.00,3.04,0.20,2.08,5.10,0.89,3.53,760
2,2,1,14.22,3.99,2.51,13.2,128,3.00,3.04,0.20,2.08,5.10,0.89,3.53,760
3,3,1,13.64,3.10,2.56,15.2,116,2.70,3.03,0.17,1.66,5.10,0.96,3.36,845
4,4,1,13.56,1.73,2.46,20.5,116,2.96,2.78,0.20,2.45,6.25,0.98,3.03,1120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,190,3,13.58,2.58,2.69,24.5,105,1.55,0.84,0.39,1.54,8.66,0.74,1.80,750
191,191,3,14.34,1.68,2.70,25.0,98,2.80,1.31,0.53,2.70,13.00,0.57,1.96,660
192,192,3,13.48,1.67,2.64,22.5,89,2.60,1.10,0.52,2.29,11.75,0.57,1.78,620
193,193,3,13.50,3.12,2.62,24.0,123,1.40,1.57,0.22,1.25,8.60,0.59,1.30,500


In [5]:
data.drop('Unnamed: 0', inplace=True, axis=1)
data.columns=["Class","a","b","c","d","e","f","g","h","i","j","k","l","m"]
data

,Class,a,b,c,d,e,f,g,h,i,j,k,l,m
0,1,14.38,3.59,2.28,16.0,102,3.25,3.17,0.27,2.19,4.90,1.04,3.44,1065
1,1,14.22,3.99,2.51,13.2,128,3.00,3.04,0.20,2.08,5.10,0.89,3.53,760
2,1,14.22,3.99,2.51,13.2,128,3.00,3.04,0.20,2.08,5.10,0.89,3.53,760
3,1,13.64,3.10,2.56,15.2,116,2.70,3.03,0.17,1.66,5.10,0.96,3.36,845
4,1,13.56,1.73,2.46,20.5,116,2.96,2.78,0.20,2.45,6.25,0.98,3.03,1120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,3,13.58,2.58,2.69,24.5,105,1.55,0.84,0.39,1.54,8.66,0.74,1.80,750
191,3,14.34,1.68,2.70,25.0,98,2.80,1.31,0.53,2.70,13.00,0.57,1.96,660
192,3,13.48,1.67,2.64,22.5,89,2.60,1.10,0.52,2.29,11.75,0.57,1.78,620
193,3,13.50,3.12,2.62,24.0,123,1.40,1.57,0.22,1.25,8.60,0.59,1.30,500


In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Class   195 non-null    int64  
 1   a       195 non-null    float64
 2   b       195 non-null    float64
 3   c       195 non-null    float64
 4   d       195 non-null    float64
 5   e       195 non-null    int64  
 6   f       195 non-null    float64
 7   g       195 non-null    float64
 8   h       195 non-null    float64
 9   i       195 non-null    float64
 10  j       195 non-null    float64
 11  k       195 non-null    float64
 12  l       195 non-null    float64
 13  m       195 non-null    int64  
dtypes: float64(11), int64(3)
memory usage: 21.5 KB


In [7]:
data

,Class,a,b,c,d,e,f,g,h,i,j,k,l,m
0,1,14.38,3.59,2.28,16.0,102,3.25,3.17,0.27,2.19,4.90,1.04,3.44,1065
1,1,14.22,3.99,2.51,13.2,128,3.00,3.04,0.20,2.08,5.10,0.89,3.53,760
2,1,14.22,3.99,2.51,13.2,128,3.00,3.04,0.20,2.08,5.10,0.89,3.53,760
3,1,13.64,3.10,2.56,15.2,116,2.70,3.03,0.17,1.66,5.10,0.96,3.36,845
4,1,13.56,1.73,2.46,20.5,116,2.96,2.78,0.20,2.45,6.25,0.98,3.03,1120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,3,13.58,2.58,2.69,24.5,105,1.55,0.84,0.39,1.54,8.66,0.74,1.80,750
191,3,14.34,1.68,2.70,25.0,98,2.80,1.31,0.53,2.70,13.00,0.57,1.96,660
192,3,13.48,1.67,2.64,22.5,89,2.60,1.10,0.52,2.29,11.75,0.57,1.78,620
193,3,13.50,3.12,2.62,24.0,123,1.40,1.57,0.22,1.25,8.60,0.59,1.30,500


In [8]:
data.Class = pd.factorize(data.Class)[0] + 1

In [9]:
gb=data.groupby("Class")

In [10]:
for Class, Class_df in gb:
    print(Class)
    print(Class_df)

1
    Class      a     b     c     d    e     f     g     h     i     j     k  \
0       1  14.38  3.59  2.28  16.0  102  3.25  3.17  0.27  2.19  4.90  1.04   
1       1  14.22  3.99  2.51  13.2  128  3.00  3.04  0.20  2.08  5.10  0.89   
2       1  14.22  3.99  2.51  13.2  128  3.00  3.04  0.20  2.08  5.10  0.89   
3       1  13.64  3.10  2.56  15.2  116  2.70  3.03  0.17  1.66  5.10  0.96   
4       1  13.56  1.73  2.46  20.5  116  2.96  2.78  0.20  2.45  6.25  0.98   
..    ...    ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...   
60      1  14.10  2.02  2.40  18.8  103  2.75  2.92  0.32  2.38  6.20  1.07   
61      1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97  6.75  1.05   
62      1  13.41  3.84  2.12  18.8   90  2.45  2.68  0.27  1.48  4.28  0.91   
63      1  13.24  3.98  2.29  17.5  103  2.64  2.63  0.32  1.66  4.36  0.82   
64      1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05   

       l     m  
0   3.44  1065  
1   3.53   760 

In [11]:
gb.get_group(1)

,Class,a,b,c,d,e,f,g,h,i,j,k,l,m
0,1,14.38,3.59,2.28,16.0,102,3.25,3.17,0.27,2.19,4.90,1.04,3.44,1065
1,1,14.22,3.99,2.51,13.2,128,3.00,3.04,0.20,2.08,5.10,0.89,3.53,760
2,1,14.22,3.99,2.51,13.2,128,3.00,3.04,0.20,2.08,5.10,0.89,3.53,760
3,1,13.64,3.10,2.56,15.2,116,2.70,3.03,0.17,1.66,5.10,0.96,3.36,845
4,1,13.56,1.73,2.46,20.5,116,2.96,2.78,0.20,2.45,6.25,0.98,3.03,1120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,1,14.10,2.02,2.40,18.8,103,2.75,2.92,0.32,2.38,6.20,1.07,2.75,1060
61,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450
62,1,13.41,3.84,2.12,18.8,90,2.45,2.68,0.27,1.48,4.28,0.91,3.00,1035
63,1,13.24,3.98,2.29,17.5,103,2.64,2.63,0.32,1.66,4.36,0.82,3.00,680


In [12]:
class_samples=gb.get_group(1).sample(n=15)
#    print(class_samples)

In [13]:
print(type(class_samples))

<class 'pandas.core.frame.DataFrame'>


In [14]:
mean_sum=class_samples["a"].mean() + class_samples["b"].mean() + class_samples["c"].mean() + class_samples["d"].mean() + class_samples["e"].mean()  + class_samples["f"].mean()  + class_samples["g"].mean()  + class_samples["h"].mean()  + class_samples["i"].mean()  + class_samples["j"].mean() + class_samples["k"].mean()  + class_samples["l"].mean() + class_samples["m"].mean()

In [15]:
column_length=len(data.columns) -1

In [16]:
similar_val_1=mean_sum/column_length
print(similar_val_1)

88.1462564102564


In [17]:
class_2_samples=gb.get_group(2).sample(n=15)
#    print(class_2_samples)

In [18]:
mean_sum_2=class_2_samples["a"].mean() + class_2_samples["b"].mean() + class_2_samples["c"].mean() + class_2_samples["d"].mean()  + class_2_samples["e"].mean()  + class_2_samples["f"].mean()  + class_2_samples["g"].mean() + class_2_samples["h"].mean() + class_2_samples["i"].mean()  + class_2_samples["j"].mean() + class_2_samples["k"].mean() + class_2_samples["l"].mean()  + class_2_samples["m"].mean()

In [19]:
similar_val_2=mean_sum_2/column_length
print(similar_val_2)

50.93121025641025


In [20]:
class_3_samples=gb.get_group(3).sample(n=15)
#    print(class_3_samples)

In [21]:
mean_sum_3=class_3_samples["a"].mean() + class_3_samples["b"].mean() + class_3_samples["c"].mean() + class_3_samples["d"].mean() + class_3_samples["e"].mean() + class_3_samples["f"].mean() + class_3_samples["g"].mean() + class_3_samples["h"].mean() + class_3_samples["i"].mean()  + class_3_samples["j"].mean() + class_3_samples["k"].mean() + class_3_samples["l"].mean() + class_3_samples["m"].mean()

In [22]:
similar_val_3=mean_sum_3/column_length
print(similar_val_3)

61.65630769230769


In [23]:
sim_23=abs(similar_val_3 - similar_val_2)
sim_23=sim_23/100
sim_23=1 - sim_23

sim_12=abs(similar_val_1 - similar_val_2)
sim_12=sim_12/100
sim_12=1 - sim_12

sim_13=abs(similar_val_3 - similar_val_1)
sim_13=sim_13/100
sim_13=1 - sim_13

print("Similarity between 2 and 3: ", sim_23)
print("Similarity between 2 and 1: ", sim_12)
print("Similarity between 1 and 3: ", sim_13)

Similarity between 2 and 3:  0.8927490256410257
Similarity between 2 and 1:  0.6278495384615386
Similarity between 1 and 3:  0.7351005128205129


In [24]:
gb.size()

Class
1    65
2    65
3    65
dtype: int64

In [25]:
m=math.ceil((71+59)/2)

In [26]:
print(m)

65


In [27]:
len(gb)

3

In [28]:
neigh = KNeighborsClassifier(n_neighbors=5)

In [29]:
#neigh.fit(X_train, Y_train)
neigh.fit(data, data.Class)

KNeighborsClassifier()

In [30]:
result=neigh.kneighbors(data, return_distance=True)

In [31]:
print(type(result))

<class 'tuple'>


In [32]:
print(result)

(array([[  0.        ,   6.23825296,  16.07347193,  16.9427064 ,
         16.9427064 ],
       [  0.        ,   0.        ,   0.        ,  20.44215987,
         20.44215987],
       [  0.        ,   0.        ,   0.        ,  20.44215987,
         20.44215987],
       [  0.        ,   0.        ,   9.80555455,  12.33967585,
         13.45056133],
       [  0.        ,   0.        ,   0.        ,  10.1335137 ,
         10.1335137 ],
       [  0.        ,   0.        ,   0.        ,  22.68218684,
         24.58831226],
       [  0.        ,   0.        ,   0.        ,  22.68218684,
         24.58831226],
       [  0.        ,   0.        ,  25.17260018,  25.85940448,
         27.88866616],
       [  0.        ,   0.        ,   0.        ,  20.44215987,
         20.44215987],
       [  0.        ,   0.        ,  12.2969915 ,  12.2969915 ,
         44.35228743],
       [  0.        ,  11.31886478,  11.31886478,  11.31886478,
         13.66381352],
       [  0.        ,   5.29867908,   9.81

In [33]:
arr1=result[0]

In [34]:
print(type(arr1))

<class 'numpy.ndarray'>


In [35]:
print(arr1.ndim)

2


In [36]:
arr2=result[1]

In [37]:
print(type(arr2))

<class 'numpy.ndarray'>


In [38]:
print(arr1.ndim)

2


In [39]:
print(arr2)

[[  0  60  64  54  41]
 [  1   2   8  50  40]
 [  1   2   8  50  40]
 [  3  34 167 136 142]
 [ 35   4  39  17  32]
 [  5   6  23  49  30]
 [  5   6  23  49  30]
 [  7  38  55  53  33]
 [  1   2   8  50  40]
 [ 14   9  16  24  43]
 [ 10 144 142 163 167]
 [ 11  45  33  53  42]
 [ 18  12  87 116 170]
 [ 41  13  54  60   0]
 [ 14   9  16  24  43]
 [ 15  59  56  63 155]
 [ 16  24  14   9  43]
 [ 32  17   4  39  35]
 [ 18  12  87 116 170]
 [ 19  21  79 136   3]
 [ 20  52  27  62  64]
 [ 21  19  79 136  34]
 [ 22  33  31  11  53]
 [  5   6  23  49  30]
 [ 16  24  14   9  43]
 [ 25  31  22  28  42]
 [ 26  58  61  46  55]
 [ 27  62  20  64  52]
 [ 42  28  11  31  45]
 [ 29  36 143 136   3]
 [ 57  51  30  49   5]
 [ 31  42  28  22  11]
 [ 32  17   4  39  35]
 [ 33  45  11  53  22]
 [  3  34 167 136 142]
 [ 35   4  39  17  32]
 [ 29  36 143 136   3]
 [ 44  37  43  17  32]
 [  7  38  55  53  33]
 [ 35   4  39  17  32]
 [ 50  40  48   8   1]
 [ 41  13  54  60   0]
 [ 42  28  11  31  45]
 [ 43  44  

In [40]:
print(arr1)

[[  0.           6.23825296  16.07347193  16.9427064   16.9427064 ]
 [  0.           0.           0.          20.44215987  20.44215987]
 [  0.           0.           0.          20.44215987  20.44215987]
 [  0.           0.           9.80555455  12.33967585  13.45056133]
 [  0.           0.           0.          10.1335137   10.1335137 ]
 [  0.           0.           0.          22.68218684  24.58831226]
 [  0.           0.           0.          22.68218684  24.58831226]
 [  0.           0.          25.17260018  25.85940448  27.88866616]
 [  0.           0.           0.          20.44215987  20.44215987]
 [  0.           0.          12.2969915   12.2969915   44.35228743]
 [  0.          11.31886478  11.31886478  11.31886478  13.66381352]
 [  0.           5.29867908   9.81115691  10.34467496  15.09685066]
 [  0.           0.          17.75686065  17.75686065  20.87256573]
 [  0.           0.           0.          15.23137223  16.9427064 ]
 [  0.           0.          12.2969915   12.296

In [41]:
#print(arr1)

In [42]:
print(arr1.size)

975


In [43]:
#tHIS LINE TAKES THE SUMMATION OF A THE DISTANCE BETWEEN THE INSTANCE AND IT'S NEIGHBORS
addVal=[]
s=1
for i in arr1:
    _sum=int(i[0] + i[1] + i[2] + i[3] + i[4])
    addVal.append(_sum)
    print(i ," ", _sum, " ") 
    s=s+1

[ 0.          6.23825296 16.07347193 16.9427064  16.9427064 ]   56  
[ 0.          0.          0.         20.44215987 20.44215987]   40  
[ 0.          0.          0.         20.44215987 20.44215987]   40  
[ 0.          0.          9.80555455 12.33967585 13.45056133]   35  
[ 0.         0.         0.        10.1335137 10.1335137]   20  
[ 0.          0.          0.         22.68218684 24.58831226]   47  
[ 0.          0.          0.         22.68218684 24.58831226]   47  
[ 0.          0.         25.17260018 25.85940448 27.88866616]   78  
[ 0.          0.          0.         20.44215987 20.44215987]   40  
[ 0.          0.         12.2969915  12.2969915  44.35228743]   68  
[ 0.         11.31886478 11.31886478 11.31886478 13.66381352]   47  
[ 0.          5.29867908  9.81115691 10.34467496 15.09685066]   40  
[ 0.          0.         17.75686065 17.75686065 20.87256573]   56  
[ 0.          0.          0.         15.23137223 16.9427064 ]   32  
[ 0.          0.         12.2969915  12

In [44]:
print(len(addVal))

195


In [45]:
#THE VALUE FOR THE SUMMATION OF ALL THE DISTANCES
print(addVal)

[56, 40, 40, 35, 20, 47, 47, 78, 40, 68, 47, 40, 56, 32, 68, 6, 61, 30, 56, 94, 69, 81, 95, 47, 61, 178, 192, 58, 50, 57, 31, 78, 30, 49, 35, 20, 57, 67, 78, 20, 58, 32, 50, 68, 67, 40, 372, 101, 99, 42, 58, 31, 73, 52, 32, 116, 6, 31, 192, 6, 49, 192, 65, 6, 65, 51, 55, 73, 57, 41, 54, 54, 30, 7, 27, 33, 55, 54, 22, 74, 70, 55, 22, 81, 47, 7, 31, 32, 48, 57, 29, 56, 85, 47, 7, 22, 38, 30, 29, 51, 165, 39, 29, 41, 36, 37, 22, 46, 38, 30, 57, 30, 46, 30, 17, 47, 32, 165, 73, 33, 7, 171, 47, 17, 62, 30, 56, 48, 60, 17, 32, 32, 7, 38, 3, 55, 60, 57, 38, 103, 5, 48, 16, 72, 16, 5, 66, 19, 17, 65, 27, 5, 19, 72, 44, 21, 57, 22, 17, 22, 7, 17, 26, 16, 26, 30, 17, 25, 106, 29, 3, 51, 17, 32, 40, 55, 26, 78, 32, 66, 7, 22, 26, 40, 3, 37, 19, 17, 62, 5, 3, 51, 25, 51, 30]


In [46]:
arr3=np.array(addVal)

In [47]:
print(type(arr3))

<class 'numpy.ndarray'>


In [48]:
print(arr3.size)

195


In [49]:
print(arr3)

[ 56  40  40  35  20  47  47  78  40  68  47  40  56  32  68   6  61  30
  56  94  69  81  95  47  61 178 192  58  50  57  31  78  30  49  35  20
  57  67  78  20  58  32  50  68  67  40 372 101  99  42  58  31  73  52
  32 116   6  31 192   6  49 192  65   6  65  51  55  73  57  41  54  54
  30   7  27  33  55  54  22  74  70  55  22  81  47   7  31  32  48  57
  29  56  85  47   7  22  38  30  29  51 165  39  29  41  36  37  22  46
  38  30  57  30  46  30  17  47  32 165  73  33   7 171  47  17  62  30
  56  48  60  17  32  32   7  38   3  55  60  57  38 103   5  48  16  72
  16   5  66  19  17  65  27   5  19  72  44  21  57  22  17  22   7  17
  26  16  26  30  17  25 106  29   3  51  17  32  40  55  26  78  32  66
   7  22  26  40   3  37  19  17  62   5   3  51  25  51  30]


In [50]:
g=1
for i in addVal:
    print(g ," ", i) 
    g=g+1

1   56
2   40
3   40
4   35
5   20
6   47
7   47
8   78
9   40
10   68
11   47
12   40
13   56
14   32
15   68
16   6
17   61
18   30
19   56
20   94
21   69
22   81
23   95
24   47
25   61
26   178
27   192
28   58
29   50
30   57
31   31
32   78
33   30
34   49
35   35
36   20
37   57
38   67
39   78
40   20
41   58
42   32
43   50
44   68
45   67
46   40
47   372
48   101
49   99
50   42
51   58
52   31
53   73
54   52
55   32
56   116
57   6
58   31
59   192
60   6
61   49
62   192
63   65
64   6
65   65
66   51
67   55
68   73
69   57
70   41
71   54
72   54
73   30
74   7
75   27
76   33
77   55
78   54
79   22
80   74
81   70
82   55
83   22
84   81
85   47
86   7
87   31
88   32
89   48
90   57
91   29
92   56
93   85
94   47
95   7
96   22
97   38
98   30
99   29
100   51
101   165
102   39
103   29
104   41
105   36
106   37
107   22
108   46
109   38
110   30
111   57
112   30
113   46
114   30
115   17
116   47
117   32
118   165
119   73
120   33
121   7
122   171
123   47

In [51]:
newarr = arr3.reshape(195, 1)

In [52]:
print(newarr.ndim)

2


In [53]:
new_arr2=np.append(arr2, newarr, axis=1)

In [54]:
print(type(new_arr2))

<class 'numpy.ndarray'>


In [55]:
#FORM AN ARRAY THAT INCLUDES THE INDICE OF NEIGHBORS AND THE DISTANCE AS THE LAST INDICE
print(new_arr2)

[[  0  60  64  54  41  56]
 [  1   2   8  50  40  40]
 [  1   2   8  50  40  40]
 ...
 [192 166 187 148 165  25]
 [171 193  93 122 146  51]
 [165 194 192 187 166  30]]


In [56]:
print(new_arr2[0])

[ 0 60 64 54 41 56]


In [57]:
arr2

array([[  0,  60,  64,  54,  41],
       [  1,   2,   8,  50,  40],
       [  1,   2,   8,  50,  40],
       [  3,  34, 167, 136, 142],
       [ 35,   4,  39,  17,  32],
       [  5,   6,  23,  49,  30],
       [  5,   6,  23,  49,  30],
       [  7,  38,  55,  53,  33],
       [  1,   2,   8,  50,  40],
       [ 14,   9,  16,  24,  43],
       [ 10, 144, 142, 163, 167],
       [ 11,  45,  33,  53,  42],
       [ 18,  12,  87, 116, 170],
       [ 41,  13,  54,  60,   0],
       [ 14,   9,  16,  24,  43],
       [ 15,  59,  56,  63, 155],
       [ 16,  24,  14,   9,  43],
       [ 32,  17,   4,  39,  35],
       [ 18,  12,  87, 116, 170],
       [ 19,  21,  79, 136,   3],
       [ 20,  52,  27,  62,  64],
       [ 21,  19,  79, 136,  34],
       [ 22,  33,  31,  11,  53],
       [  5,   6,  23,  49,  30],
       [ 16,  24,  14,   9,  43],
       [ 25,  31,  22,  28,  42],
       [ 26,  58,  61,  46,  55],
       [ 27,  62,  20,  64,  52],
       [ 42,  28,  11,  31,  45],
       [ 29,  

In [58]:
print(new_arr2[0][1],  new_arr2[0][2],  new_arr2[0][3], new_arr2[0][4],new_arr2[0][5])

60 64 54 41 56


In [59]:
data

,Class,a,b,c,d,e,f,g,h,i,j,k,l,m
0,1,14.38,3.59,2.28,16.0,102,3.25,3.17,0.27,2.19,4.90,1.04,3.44,1065
1,1,14.22,3.99,2.51,13.2,128,3.00,3.04,0.20,2.08,5.10,0.89,3.53,760
2,1,14.22,3.99,2.51,13.2,128,3.00,3.04,0.20,2.08,5.10,0.89,3.53,760
3,1,13.64,3.10,2.56,15.2,116,2.70,3.03,0.17,1.66,5.10,0.96,3.36,845
4,1,13.56,1.73,2.46,20.5,116,2.96,2.78,0.20,2.45,6.25,0.98,3.03,1120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,3,13.58,2.58,2.69,24.5,105,1.55,0.84,0.39,1.54,8.66,0.74,1.80,750
191,3,14.34,1.68,2.70,25.0,98,2.80,1.31,0.53,2.70,13.00,0.57,1.96,660
192,3,13.48,1.67,2.64,22.5,89,2.60,1.10,0.52,2.29,11.75,0.57,1.78,620
193,3,13.50,3.12,2.62,24.0,123,1.40,1.57,0.22,1.25,8.60,0.59,1.30,500


In [60]:
# Creating and populating a dictionary with the 'key' as key and class value as value
new_dist={}
for i, v in data.Class.iteritems():
    new_dist[i]=v

In [61]:
#print(new_dist)

In [62]:
# Creating and populating a dictionary with the 's=0 to end' as key and class value as value
new_dist2={}
s=0
for i, v in data.Class.iteritems():
    new_dist2[s]=v
    s=s+1

In [63]:
#print(new_dist2)

In [64]:
# Creating and populating a dictionary with the 's=0 to end' as key and 'index value' as value
new_dist3={}
s=0
for i, v in data.Class.iteritems():
    new_dist3[s]=i
    s=s+1

In [65]:
#print(new_dist3)

In [66]:
#print(new_dist[204])

In [67]:
#new_dist3

<!-- Populating a dictionary  -->

In [68]:
    neigh_count=[]
    s=0
    for i, v in new_dist2.items():
        c1=0
        c2=0
        c3=0
        class_example=0
        
        if int(v) == 1:
            c1=c1+1
        elif int(v) == 2:
            c2=c2+1
        else:
            c3=c3+1
            
        for x in range(1,5):
            if new_dist2[new_arr2[i][x]]==1:
                c1=c1+1
            elif new_dist2[new_arr2[i][x]]==2:
                c2=c2+1
            else:
                c3=c3+1
            if int(v) == 1:
                safe_level=(1 * c1 + sim_12 * c2 + sim_13 * c3)/5
                class_example=1
                safe_level=round(safe_level,2)
            elif int(v) == 2:
                safe_level=(sim_12 * c1 + 1 * c2 + sim_23 * c3)/5
                class_example=2
                safe_level=round(safe_level,2)
            else:
                safe_level=(sim_13 * c1 + sim_23 * c2 + 1 * c3)/5
                class_example=3
                safe_level=round(safe_level,2)
        neigh_count.append([i,new_dist3[i],class_example,c1,c2,c3,safe_level,new_arr2[i][5]])
        #print(i," ",new_dist3[i]," ",class_example," ",c1," ",c2," ",c3," ",safe_level," ",new_arr2[i][5])
        #print(i," ",new_dist3[i]," ",c1," ",c2," ",c3," ",new_arr2[i][5])
    #real_new=new_dist3[i]," ",new_arr2[i][1]," ",new_arr2[i][2]," ",new_arr2[i][3]," ",new_arr2[i][4]," ",new_arr2[i][5]
    
    #print(i," ",real_new)

In [69]:
print(neigh_count)

[[0, 0, 1, 5, 0, 0, 1.0, 56], [1, 1, 1, 5, 0, 0, 1.0, 40], [2, 2, 1, 5, 0, 0, 1.0, 40], [3, 3, 1, 2, 0, 3, 0.84, 35], [4, 4, 1, 5, 0, 0, 1.0, 20], [5, 5, 1, 5, 0, 0, 1.0, 47], [6, 6, 1, 5, 0, 0, 1.0, 47], [7, 7, 1, 5, 0, 0, 1.0, 78], [8, 8, 1, 5, 0, 0, 1.0, 40], [9, 9, 1, 5, 0, 0, 1.0, 68], [10, 10, 1, 1, 0, 4, 0.79, 47], [11, 11, 1, 5, 0, 0, 1.0, 40], [12, 12, 1, 2, 2, 1, 0.8, 56], [13, 13, 1, 5, 0, 0, 1.0, 32], [14, 14, 1, 5, 0, 0, 1.0, 68], [15, 15, 1, 4, 0, 1, 0.95, 6], [16, 16, 1, 5, 0, 0, 1.0, 61], [17, 17, 1, 5, 0, 0, 1.0, 30], [18, 18, 1, 2, 2, 1, 0.8, 56], [19, 19, 1, 3, 1, 1, 0.87, 94], [20, 20, 1, 5, 0, 0, 1.0, 69], [21, 21, 1, 3, 1, 1, 0.87, 81], [22, 22, 1, 5, 0, 0, 1.0, 95], [23, 23, 1, 5, 0, 0, 1.0, 47], [24, 24, 1, 5, 0, 0, 1.0, 61], [25, 25, 1, 5, 0, 0, 1.0, 178], [26, 26, 1, 5, 0, 0, 1.0, 192], [27, 27, 1, 5, 0, 0, 1.0, 58], [28, 28, 1, 5, 0, 0, 1.0, 50], [29, 29, 1, 3, 0, 2, 0.89, 57], [30, 30, 1, 5, 0, 0, 1.0, 31], [31, 31, 1, 5, 0, 0, 1.0, 78], [32, 32, 1, 5, 0, 0,

In [70]:
# iterating a dictionary

In [71]:
# for s in range(149):
#     print(neigh_count[s])

In [72]:
# Converting a dictionary to a dataframe

In [73]:
new_main_df = pd.DataFrame(neigh_count,columns=['s_no','real_index','Class','c_one','c_two','c_three','safe_level','distance'])

In [74]:
#print(new_main_df)

In [75]:
new_main_df.set_index("s_no", inplace=True)

In [76]:
print(new_main_df)

      real_index  Class  c_one  c_two  c_three  safe_level  distance
s_no                                                                
0              0      1      5      0        0        1.00        56
1              1      1      5      0        0        1.00        40
2              2      1      5      0        0        1.00        40
3              3      1      2      0        3        0.84        35
4              4      1      5      0        0        1.00        20
...          ...    ...    ...    ...      ...         ...       ...
190          190      3      0      0        5        1.00         3
191          191      3      0      1        4        0.98        51
192          192      3      0      0        5        1.00        25
193          193      3      0      2        3        0.96        51
194          194      3      0      0        5        1.00        30

[195 rows x 7 columns]


In [77]:
# iterating through a dataframe, the following methods can be used .iterrows() 
# and itertuples() but itertuples is preferred because it keeps the data types and more

In [78]:
# for index, row in new_main_df.iterrows():
#     print(index, row['real_index'], row['class'], row['c_one'], row['c_two'], row['c_three'], row['safe_level'], row['distance'] )

In [79]:
for i, row in enumerate(new_main_df.itertuples(), 0):
    print(i, row.real_index)
    

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 10
11 11
12 12
13 13
14 14
15 15
16 16
17 17
18 18
19 19
20 20
21 21
22 22
23 23
24 24
25 25
26 26
27 27
28 28
29 29
30 30
31 31
32 32
33 33
34 34
35 35
36 36
37 37
38 38
39 39
40 40
41 41
42 42
43 43
44 44
45 45
46 46
47 47
48 48
49 49
50 50
51 51
52 52
53 53
54 54
55 55
56 56
57 57
58 58
59 59
60 60
61 61
62 62
63 63
64 64
65 65
66 66
67 67
68 68
69 69
70 70
71 71
72 72
73 73
74 74
75 75
76 76
77 77
78 78
79 79
80 80
81 81
82 82
83 83
84 84
85 85
86 86
87 87
88 88
89 89
90 90
91 91
92 92
93 93
94 94
95 95
96 96
97 97
98 98
99 99
100 100
101 101
102 102
103 103
104 104
105 105
106 106
107 107
108 108
109 109
110 110
111 111
112 112
113 113
114 114
115 115
116 116
117 117
118 118
119 119
120 120
121 121
122 122
123 123
124 124
125 125
126 126
127 127
128 128
129 129
130 130
131 131
132 132
133 133
134 134
135 135
136 136
137 137
138 138
139 139
140 140
141 141
142 142
143 143
144 144
145 145
146 146
147 147
148 148
149 149
150 150
151 151
152 

In [80]:
new_classes=new_main_df.groupby("Class")

In [81]:
new_classes.size()

Class
1    65
2    65
3    65
dtype: int64

In [82]:
new_class_1=new_classes.get_group(1)
safe_exam=0
border_exam=0
rare_exam=0
outlier_exam=0
for i, row in enumerate(new_class_1.itertuples(index=True), 0):
    if(row.c_one==5 or row.c_one==4):
        safe_exam=safe_exam + 1
    elif(row.c_one==3 or row.c_one==2):
        border_exam=border_exam + 1
    elif(row.c_one==1):
        rare_exam=rare_exam + 1
    else:
        outlier_exam=outlier_exam + 1
print(safe_exam,border_exam,rare_exam,outlier_exam)

55 9 1 0


In [83]:
new_class_2=new_classes.get_group(2)
safe_exam=0
border_exam=0
rare_exam=0
outlier_exam=0
for i, row in enumerate(new_class_2.itertuples(index=True), 0):
    if(row.c_two==5 or row.c_two==4):
        safe_exam=safe_exam + 1
    elif(row.c_two==3 or row.c_one==2):
        border_exam=border_exam + 1
    elif(row.c_two==1):
        rare_exam=rare_exam + 1
    else:
        outlier_exam=outlier_exam + 1
print(safe_exam,border_exam,rare_exam,outlier_exam)

43 9 6 7


In [84]:
new_class_3=new_classes.get_group(3)
safe_exam=0
border_exam=0
rare_exam=0
outlier_exam=0
for i, row in enumerate(new_class_3.itertuples(index=True), 0):
    if(row.c_three==5 or row.c_three==4):
        safe_exam=safe_exam + 1
    elif(row.c_three==3 or row.c_one==2):
        border_exam=border_exam + 1
    elif(row.c_three==1):
        rare_exam=rare_exam + 1
    else:
        outlier_exam=outlier_exam + 1
print(safe_exam,border_exam,rare_exam,outlier_exam)

46 8 2 9


In [85]:
# for row in new_main_df.itertuples():
#     print(getattr(row, 'real_index'), getattr(row, 'c_one'))

In [86]:
new_gb=new_main_df.groupby("Class")

In [87]:
new_1=new_gb.get_group(1).sort_values(['safe_level', 'distance'], ascending=[False, False])

In [88]:
#new_1

In [89]:
#new_2=new_gb.get_group(2)

In [90]:
#new_3=new_gb.get_group(3)

In [91]:
gb_1=gb.get_group(1)

In [92]:
gb_2=gb.get_group(2)

In [93]:
gb_3=gb.get_group(3)

In [94]:
#new_gb.get_group(1).sort_values(['safe_level', 'distance'], ascending=[False, False])

In [95]:
new_2=new_gb.get_group(2).sort_values(['safe_level', 'distance'], ascending=[False, False])

In [96]:
#new_2

In [97]:
#for dropping some index with less simlar neigbour
#new_2.drop(new_2[new_2['c_two'] < 4].index, inplace=True)

In [98]:
#new_2

In [99]:
#b=len(new_2.index)

In [100]:
#print(b)

In [101]:
#s=m - b

In [102]:
#print(s)

In [103]:
#if(s>b):
    #minor_c_2=new_2.sample(n=b, replace='False')
    #print(len(minor_c_2.index))
    #minor_c_2=minor_c_2.sample(n=b, replace='True')
    #print(len(minor_c_2.index))

In [104]:
#u=len(minor_c_2.index)

In [105]:
#print(u)

In [106]:
minor_c_2=new_2.sample(n=m, replace='False')
print(minor_c_2)

      real_index  Class  c_one  c_two  c_three  safe_level  distance
s_no                                                                
122          122      2      0      2        3        0.94        47
81            81      2      0      5        0        1.00        55
118          118      2      0      5        0        1.00        73
79            79      2      3      1        1        0.76        74
123          123      2      0      4        1        0.98        17
...          ...    ...    ...    ...      ...         ...       ...
81            81      2      0      5        0        1.00        55
83            83      2      0      1        4        0.91        81
96            96      2      0      5        0        1.00        38
77            77      2      0      5        0        1.00        54
107          107      2      0      5        0        1.00        46

[65 rows x 7 columns]


In [107]:
new_3=new_gb.get_group(3).sort_values(['safe_level', 'distance'], ascending=[False, True])

In [108]:
#for dropping some index with less simlar neigbour
#new_3.drop(new_3[new_3['c_three'] < 4].index, inplace=True)

In [109]:
minor_c_1=new_1.sample(n=m, replace='False')
print(minor_c_1)

      real_index  Class  c_one  c_two  c_three  safe_level  distance
s_no                                                                
39            39      1      5      0        0        1.00        20
53            53      1      5      0        0        1.00        52
25            25      1      5      0        0        1.00       178
20            20      1      5      0        0        1.00        69
36            36      1      3      0        2        0.89        57
...          ...    ...    ...    ...      ...         ...       ...
20            20      1      5      0        0        1.00        69
50            50      1      5      0        0        1.00        58
39            39      1      5      0        0        1.00        20
40            40      1      5      0        0        1.00        58
38            38      1      5      0        0        1.00        78

[65 rows x 7 columns]


In [110]:
new_gb

In [111]:
gb

In [112]:
#new_1

In [113]:
#new_1.drop(new_1[new_1['c_one'] < 5].index, inplace=True)

In [114]:
#new_1

In [115]:
#for i, row in enumerate(new_1.itertuples(index=True), 0):
    #print(i, row.Index, row.real_index, row.Class, row.c_one, row.c_two, row.c_three, row.safe_level, row.distance)

In [116]:
#r=len(new_1.index)-m

In [117]:
#print(r)

In [118]:
minor_c_3=new_3.sample(n=m, replace='False')
print(minor_c_3)


      real_index  Class  c_one  c_two  c_three  safe_level  distance
s_no                                                                
154          154      3      0      3        2        0.94        44
189          189      3      0      0        5        1.00         5
169          169      3      0      1        4        0.98        29
138          138      3      0      4        1        0.91        38
191          191      3      0      1        4        0.98        51
...          ...    ...    ...    ...      ...         ...       ...
193          193      3      0      2        3        0.96        51
156          156      3      0      1        4        0.98        57
148          148      3      0      0        5        1.00        17
138          138      3      0      4        1        0.91        38
132          132      3      0      0        5        1.00         7

[65 rows x 7 columns]


In [119]:
#for i, row in enumerate(major_c_1.itertuples(index=True), 0):
    #print(i, row.real_index)

In [120]:
#how to generate a random list from an interval
#num_list = random.sample(range(0, len(new_1.index)), r)
#print(num_list)

In [121]:
maj_c_filtered=[]
for i, row in enumerate(minor_c_1.itertuples(index=True), 0):
    a=gb_1.at[row.real_index, 'Class']
    b=gb_1.at[row.real_index, 'a']
    c=gb_1.at[row.real_index, 'b']
    d=gb_1.at[row.real_index, 'c']
    e=gb_1.at[row.real_index, 'd']
    f=gb_1.at[row.real_index, 'e']
    g=gb_1.at[row.real_index, 'f']
    h=gb_1.at[row.real_index, 'g']
    i=gb_1.at[row.real_index, 'h']
    j=gb_1.at[row.real_index, 'i']
    k=gb_1.at[row.real_index, 'j']
    l=gb_1.at[row.real_index, 'k']
    m=gb_1.at[row.real_index, 'l']
    n=gb_1.at[row.real_index, 'm']
    maj_c_filtered.append([a,b,c,d,e,f,g,h,i,j,k,l,m,n])

In [122]:
print(maj_c_filtered)

[[1, 13.56, 1.73, 2.46, 20.5, 116, 2.96, 2.78, 0.2, 2.45, 6.25, 0.98, 3.03, 1120], [1, 14.39, 1.87, 2.45, 14.6, 96, 2.5, 2.52, 0.3, 1.98, 5.25, 1.02, 3.58, 1290], [1, 13.76, 1.53, 2.7, 19.5, 132, 2.95, 2.74, 0.5, 1.35, 5.4, 1.25, 3.0, 1235], [1, 13.07, 1.5, 2.1, 15.5, 98, 2.4, 2.64, 0.28, 1.37, 3.7, 1.18, 2.69, 1020], [1, 13.5, 1.81, 2.61, 20.0, 96, 2.53, 2.61, 0.28, 1.66, 3.52, 1.12, 3.82, 845], [1, 14.06, 1.63, 2.28, 16.0, 126, 3.0, 3.17, 0.24, 2.1, 5.65, 1.09, 3.71, 780], [1, 13.05, 1.73, 2.04, 12.4, 92, 2.72, 3.27, 0.17, 2.91, 7.2, 1.12, 2.91, 1150], [1, 14.2, 1.76, 2.45, 15.2, 112, 3.27, 3.39, 0.34, 1.97, 6.75, 1.05, 2.85, 1450], [1, 13.3, 1.72, 2.14, 17.0, 94, 2.4, 2.19, 0.27, 1.35, 3.95, 1.02, 2.77, 1285], [1, 13.16, 2.36, 2.67, 18.6, 101, 2.8, 3.24, 0.3, 2.81, 5.68, 1.03, 3.17, 1185], [1, 14.12, 1.48, 2.32, 16.8, 95, 2.2, 2.43, 0.26, 1.57, 5.0, 1.17, 2.82, 1280], [1, 13.68, 1.83, 2.36, 17.2, 104, 2.42, 2.69, 0.42, 1.97, 3.84, 1.23, 2.87, 990], [1, 14.22, 1.7, 2.3, 16.3, 118, 3.

In [123]:
#for i, row in enumerate(minor_c_2.itertuples(index=True), 0):
    #print(i, row.real_index)

In [124]:
min_c_2_filtered=[]
for i, row in enumerate(minor_c_2.itertuples(index=True), 0):
    a=gb_2.at[row.real_index, 'Class']
    b=gb_2.at[row.real_index, 'a']
    c=gb_2.at[row.real_index, 'b']
    d=gb_2.at[row.real_index, 'c']
    e=gb_2.at[row.real_index, 'd']
    f=gb_2.at[row.real_index, 'e']
    g=gb_2.at[row.real_index, 'f']
    h=gb_2.at[row.real_index, 'g']
    i=gb_2.at[row.real_index, 'h']
    j=gb_2.at[row.real_index, 'i']
    k=gb_2.at[row.real_index, 'j']
    l=gb_2.at[row.real_index, 'k']
    m=gb_2.at[row.real_index, 'l']
    n=gb_2.at[row.real_index, 'm']
    min_c_2_filtered.append([a,b,c,d,e,f,g,h,i,j,k,l,m,n])

In [125]:
print(min_c_2_filtered)

[[2, 11.84, 2.89, 2.23, 18.0, 112, 1.72, 1.32, 0.43, 0.95, 2.65, 0.96, 2.52, 500], [2, 12.42, 1.61, 2.19, 22.5, 108, 2.0, 2.09, 0.34, 1.61, 2.06, 1.06, 2.96, 345], [2, 12.29, 2.83, 2.22, 18.0, 88, 2.45, 2.25, 0.25, 1.99, 2.15, 1.15, 3.3, 290], [2, 12.29, 1.61, 2.21, 20.4, 103, 1.1, 1.02, 0.37, 1.46, 3.05, 0.906, 1.82, 870], [2, 13.49, 1.66, 2.24, 24.0, 87, 1.88, 1.84, 0.27, 1.03, 3.74, 0.98, 2.78, 472], [2, 11.64, 2.06, 2.46, 21.6, 84, 1.95, 1.69, 0.48, 1.35, 2.8, 1.0, 2.75, 680], [2, 13.49, 1.66, 2.24, 24.0, 87, 1.88, 1.84, 0.27, 1.03, 3.74, 0.98, 2.78, 472], [2, 12.43, 1.53, 2.29, 21.5, 86, 2.74, 3.15, 0.39, 1.77, 3.94, 0.69, 2.84, 352], [2, 12.77, 3.43, 1.98, 16.0, 80, 1.63, 1.25, 0.43, 0.83, 3.4, 0.7, 2.12, 372], [2, 12.42, 2.55, 2.27, 22.0, 90, 1.68, 1.84, 0.66, 1.42, 2.7, 0.86, 3.3, 315], [2, 13.11, 1.01, 1.7, 15.0, 78, 2.98, 3.18, 0.26, 2.28, 5.3, 1.12, 3.18, 502], [2, 11.64, 2.06, 2.46, 21.6, 84, 1.95, 1.69, 0.48, 1.35, 2.8, 1.0, 2.75, 680], [2, 12.42, 2.55, 2.27, 22.0, 90, 1.6

In [126]:
#for i, row in enumerate(minor_c_3.itertuples(index=True), 0):
    #print(i, row.real_index)

In [127]:
min_c_3_filtered=[]
for i, row in enumerate(minor_c_3.itertuples(index=True), 0):
    a=gb_3.at[row.real_index, 'Class']
    b=gb_3.at[row.real_index, 'a']
    c=gb_3.at[row.real_index, 'b']
    d=gb_3.at[row.real_index, 'c']
    e=gb_3.at[row.real_index, 'd']
    f=gb_3.at[row.real_index, 'e']
    g=gb_3.at[row.real_index, 'f']
    h=gb_3.at[row.real_index, 'g']
    i=gb_3.at[row.real_index, 'h']
    j=gb_3.at[row.real_index, 'i']
    k=gb_3.at[row.real_index, 'j']
    l=gb_3.at[row.real_index, 'k']
    m=gb_3.at[row.real_index, 'l']
    n=gb_3.at[row.real_index, 'm']
    min_c_3_filtered.append([a,b,c,d,e,f,g,h,i,j,k,l,m,n])

In [128]:
print(min_c_3_filtered)

[[3, 13.49, 3.59, 2.19, 19.5, 88, 1.62, 0.48, 0.58, 0.88, 5.7, 0.81, 1.82, 580], [3, 12.96, 3.45, 2.35, 18.5, 106, 1.39, 0.7, 0.4, 0.94, 5.28, 0.68, 1.75, 675], [3, 12.36, 3.83, 2.38, 21.0, 88, 2.3, 0.92, 0.5, 1.04, 7.65, 0.56, 1.58, 520], [3, 12.77, 2.39, 2.28, 19.5, 86, 1.39, 0.51, 0.48, 0.64, 9.899999, 0.57, 1.63, 470], [3, 14.34, 1.68, 2.7, 25.0, 98, 2.8, 1.31, 0.53, 2.7, 13.0, 0.57, 1.96, 660], [3, 13.58, 2.58, 2.69, 24.5, 105, 1.55, 0.84, 0.39, 1.54, 8.66, 0.74, 1.8, 750], [3, 13.52, 3.17, 2.72, 23.5, 97, 1.55, 0.52, 0.5, 0.55, 4.35, 0.89, 2.06, 520], [3, 14.34, 1.68, 2.7, 25.0, 98, 2.8, 1.31, 0.53, 2.7, 13.0, 0.57, 1.96, 660], [3, 13.32, 3.24, 2.38, 21.5, 92, 1.93, 0.76, 0.45, 1.25, 8.42, 0.55, 1.62, 650], [3, 12.51, 1.24, 2.25, 17.5, 85, 2.0, 0.58, 0.6, 1.25, 5.45, 0.75, 1.51, 650], [3, 13.88, 5.04, 2.23, 20.0, 80, 0.98, 0.34, 0.4, 0.68, 4.9, 0.58, 1.33, 415], [3, 13.58, 2.58, 2.69, 24.5, 105, 1.55, 0.84, 0.39, 1.54, 8.66, 0.74, 1.8, 750], [3, 13.78, 2.76, 2.3, 22.0, 90, 1.35, 

In [129]:
new_min_c_3_filtered = pd.DataFrame(min_c_3_filtered,columns=['Class','a','b','c','d','e','f','g','h','i','j','k','l','m'])

In [130]:
print(new_min_c_3_filtered)

    Class      a     b     c     d    e     f     g     h     i          j  \
0       3  13.49  3.59  2.19  19.5   88  1.62  0.48  0.58  0.88   5.700000   
1       3  12.96  3.45  2.35  18.5  106  1.39  0.70  0.40  0.94   5.280000   
2       3  12.36  3.83  2.38  21.0   88  2.30  0.92  0.50  1.04   7.650000   
3       3  12.77  2.39  2.28  19.5   86  1.39  0.51  0.48  0.64   9.899999   
4       3  14.34  1.68  2.70  25.0   98  2.80  1.31  0.53  2.70  13.000000   
..    ...    ...   ...   ...   ...  ...   ...   ...   ...   ...        ...   
60      3  13.50  3.12  2.62  24.0  123  1.40  1.57  0.22  1.25   8.600000   
61      3  13.08  3.90  2.36  21.5  113  1.41  1.39  0.34  1.14   9.400000   
62      3  13.78  2.76  2.30  22.0   90  1.35  0.68  0.41  1.03   9.580000   
63      3  12.77  2.39  2.28  19.5   86  1.39  0.51  0.48  0.64   9.899999   
64      3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.300000   

       k     l    m  
0   0.81  1.82  580  
1   0.68  1.75  675

In [131]:
new_min_c_2_filtered = pd.DataFrame(min_c_2_filtered,columns=['Class','a','b','c','d','e','f','g','h','i','j','k','l','m'])

In [132]:
print(new_min_c_2_filtered)

    Class      a     b     c     d    e     f     g     h     i     j      k  \
0       2  11.84  2.89  2.23  18.0  112  1.72  1.32  0.43  0.95  2.65  0.960   
1       2  12.42  1.61  2.19  22.5  108  2.00  2.09  0.34  1.61  2.06  1.060   
2       2  12.29  2.83  2.22  18.0   88  2.45  2.25  0.25  1.99  2.15  1.150   
3       2  12.29  1.61  2.21  20.4  103  1.10  1.02  0.37  1.46  3.05  0.906   
4       2  13.49  1.66  2.24  24.0   87  1.88  1.84  0.27  1.03  3.74  0.980   
..    ...    ...   ...   ...   ...  ...   ...   ...   ...   ...   ...    ...   
60      2  12.42  1.61  2.19  22.5  108  2.00  2.09  0.34  1.61  2.06  1.060   
61      2  12.08  1.33  2.30  23.6   70  2.20  1.59  0.42  1.38  1.74  1.070   
62      2  12.08  1.83  2.32  18.5   81  1.60  1.50  0.52  1.64  2.40  1.080   
63      2  12.64  1.36  2.02  16.8  100  2.02  1.41  0.53  0.62  5.75  0.980   
64      2  12.77  3.43  1.98  16.0   80  1.63  1.25  0.43  0.83  3.40  0.700   

       l    m  
0   2.52  500  
1   2.9

In [133]:
new_maj_c_filtered = pd.DataFrame(maj_c_filtered,columns=['Class','a','b','c','d','e','f','g','h','i','j','k','l','m'])

In [134]:
print(new_maj_c_filtered)

    Class      a     b     c     d    e     f     g     h     i     j     k  \
0       1  13.56  1.73  2.46  20.5  116  2.96  2.78  0.20  2.45  6.25  0.98   
1       1  14.39  1.87  2.45  14.6   96  2.50  2.52  0.30  1.98  5.25  1.02   
2       1  13.76  1.53  2.70  19.5  132  2.95  2.74  0.50  1.35  5.40  1.25   
3       1  13.07  1.50  2.10  15.5   98  2.40  2.64  0.28  1.37  3.70  1.18   
4       1  13.50  1.81  2.61  20.0   96  2.53  2.61  0.28  1.66  3.52  1.12   
..    ...    ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...   
60      1  13.07  1.50  2.10  15.5   98  2.40  2.64  0.28  1.37  3.70  1.18   
61      1  14.06  1.63  2.28  16.0  126  3.00  3.17  0.24  2.10  5.65  1.09   
62      1  13.56  1.73  2.46  20.5  116  2.96  2.78  0.20  2.45  6.25  0.98   
63      1  14.06  1.63  2.28  16.0  126  3.00  3.17  0.24  2.10  5.65  1.09   
64      1  13.63  1.81  2.70  17.2  112  2.85  2.91  0.30  1.46  7.30  1.28   

       l     m  
0   3.03  1120  
1   3.58  1290  


In [135]:
result = new_maj_c_filtered.append([new_min_c_2_filtered, new_min_c_3_filtered], ignore_index='True')

In [136]:
print(result)

     Class      a     b     c     d    e     f     g     h     i         j  \
0        1  13.56  1.73  2.46  20.5  116  2.96  2.78  0.20  2.45  6.250000   
1        1  14.39  1.87  2.45  14.6   96  2.50  2.52  0.30  1.98  5.250000   
2        1  13.76  1.53  2.70  19.5  132  2.95  2.74  0.50  1.35  5.400000   
3        1  13.07  1.50  2.10  15.5   98  2.40  2.64  0.28  1.37  3.700000   
4        1  13.50  1.81  2.61  20.0   96  2.53  2.61  0.28  1.66  3.520000   
..     ...    ...   ...   ...   ...  ...   ...   ...   ...   ...       ...   
190      3  13.50  3.12  2.62  24.0  123  1.40  1.57  0.22  1.25  8.600000   
191      3  13.08  3.90  2.36  21.5  113  1.41  1.39  0.34  1.14  9.400000   
192      3  13.78  2.76  2.30  22.0   90  1.35  0.68  0.41  1.03  9.580000   
193      3  12.77  2.39  2.28  19.5   86  1.39  0.51  0.48  0.64  9.899999   
194      3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41  7.300000   

        k     l     m  
0    0.98  3.03  1120  
1    1.02  3.58

In [137]:
result.to_csv("balanced_wine.csv")

In [138]:
result=result.sample(frac=1).reset_index(drop=True)

In [139]:
result.to_csv("balanced_wine_rand.csv")

In [140]:
X_train, X_test, Y_train, Y_test = train_test_split(result, result.Class, train_size=.7)

In [141]:
categories=result.groupby("Class")

In [142]:
w=categories.size()

In [143]:
print(w)

Class
1    65
2    65
3    65
dtype: int64


In [144]:
#Loading the Classifier model
model=svm.SVC(C = 1, probability=True)
clf = DecisionTreeClassifier(random_state=0, max_depth=4)
knn = KNeighborsClassifier(n_neighbors=5)

In [145]:
#Train the model using the training sets
model.fit(X_train, Y_train)
clf = clf.fit(X_train, Y_train)
knn = knn.fit(X_train, Y_train)

In [146]:
#prule_pred_proba=prule.predict_proba(X_test)
model_pred_proba=model.predict_proba(X_test)
clf_pred_proba=clf.predict_proba(X_test)
knn_pred_proba=knn.predict_proba(X_test)

In [147]:
model_X_train_pred=model.predict(X_train)
model_X_test_pred=model.predict(X_test)
clf_X_train_pred=clf.predict(X_train)
clf_X_test_pred=clf.predict(X_test)
knn_X_train_pred=knn.predict(X_train)
knn_X_test_pred=knn.predict(X_test)

In [148]:
print("Accuracy for SVM Test Data:                        ", metrics.accuracy_score(Y_test, model_X_test_pred))
print("Accuracy for Decision Tree Classifier Test Data:   ", metrics.accuracy_score(Y_test, clf_X_test_pred))
print("Accuracy for KNN Test Data:                        ", metrics.accuracy_score(Y_test, knn_X_test_pred))


Accuracy for SVM Test Data:                         0.6779661016949152
Accuracy for Decision Tree Classifier Test Data:    1.0
Accuracy for KNN Test Data:                         0.7966101694915254


In [149]:
model_gmean=geometric_mean_score(Y_test, model_X_test_pred, average='weighted')
clf_gmean=geometric_mean_score(Y_test, clf_X_test_pred, average='weighted')
knn_gmean=geometric_mean_score(Y_test, knn_X_test_pred, average='weighted')

In [150]:
print("G mean for SVM Test Data:                           ", model_gmean)
print("G mean for Decision Tree Classifier Test Data:      ", clf_gmean)
print("G mean for KNN Test Data:                           ", knn_gmean)

G mean for SVM Test Data:                            0.7513820865665699
G mean for Decision Tree Classifier Test Data:       1.0
G mean for KNN Test Data:                            0.8415874171586847


In [151]:
cm_model_test=confusion_matrix(Y_test, model_X_test_pred)

In [152]:
cm_model_test

array([[12,  0,  4],
       [ 0, 13, 11],
       [ 0,  4, 15]], dtype=int64)

In [153]:
#disp_model = ConfusionMatrixDisplay(confusion_matrix=cm_model_test, display_labels=model.classes_)

In [154]:
#disp_model.plot() 

In [155]:
cm_clf_test=confusion_matrix(Y_test, clf_X_test_pred)

In [156]:
cm_clf_test

array([[16,  0,  0],
       [ 0, 24,  0],
       [ 0,  0, 19]], dtype=int64)

In [157]:
#disp_clf = ConfusionMatrixDisplay(confusion_matrix=cm_clf_test, display_labels=model.classes_)

In [158]:
#disp_clf.plot() 

In [159]:
cm_knn_test=confusion_matrix(Y_test, knn_X_test_pred)

In [160]:
cm_knn_test

array([[14,  1,  1],
       [ 0, 17,  7],
       [ 0,  3, 16]], dtype=int64)

In [161]:
#disp_knn = ConfusionMatrixDisplay(confusion_matrix=cm_knn_test, display_labels=model.classes_)

In [162]:
#disp_knn.plot()

In [163]:
print(metrics.classification_report(Y_test, clf_X_test_pred, digits=3))

              precision    recall  f1-score   support

           1      1.000     1.000     1.000        16
           2      1.000     1.000     1.000        24
           3      1.000     1.000     1.000        19

    accuracy                          1.000        59
   macro avg      1.000     1.000     1.000        59
weighted avg      1.000     1.000     1.000        59



In [164]:
print(metrics.classification_report(Y_test, knn_X_test_pred, digits=3))

              precision    recall  f1-score   support

           1      1.000     0.875     0.933        16
           2      0.810     0.708     0.756        24
           3      0.667     0.842     0.744        19

    accuracy                          0.797        59
   macro avg      0.825     0.808     0.811        59
weighted avg      0.815     0.797     0.800        59



In [165]:
print(metrics.classification_report(Y_test, model_X_test_pred, digits=3))

              precision    recall  f1-score   support

           1      1.000     0.750     0.857        16
           2      0.765     0.542     0.634        24
           3      0.500     0.789     0.612        19

    accuracy                          0.678        59
   macro avg      0.755     0.694     0.701        59
weighted avg      0.743     0.678     0.688        59



In [166]:
model_cvp=cross_val_predict(model, X_test, Y_test, cv=3, method="predict")

In [167]:
roc_auc_score(Y_test, model_pred_proba, multi_class='ovr')

0.8815082765052166